-- Add has_image column to comedians table
ALTER TABLE comedians ADD COLUMN has_image BOOLEAN NOT NULL DEFAULT false;

-- Populate has_image for 1844 comedians with existing CDN images
UPDATE comedians SET has_image = true WHERE name IN (
  'A-Train', 'Aamir Hassan', 'Aaron Berg', 'Aaron Chen', 'Aaron Jackson', 'Aaron McCann', 'Abbas Wahab', 'Abby Govindan', 'Abby Washuta', 'Adam Cayton-Holland',
  'Adam Conover', 'Adam Ferrara', 'Adam Friedland', 'Adam Gabel', 'Adam Gilbert', 'Adam Gulley', 'Adam Hmada', 'Adam Hunter', 'Adam Mamawala', 'Adam Muller',
  'Adam Rowe', 'Adam Smith', 'Adam Strauss', 'Adele Givens', 'Aditya Shankar', 'Adrian Smith', 'Adrien Pellerin', 'Adrienne Ianniciello', 'Adrienne Iapalucci', 'Agnes Berry',
  'Ahamed Weinberg', 'Ahmed Al-kadri', 'Ahri Findling', 'Aida Rodriguez', 'Aidan Bishop', 'Aidan Kelly', 'Aiden Bishop', 'Akaash Singh', 'Akeem Woods', 'Al Lubel',
  'Al Madrigal', 'Alaina Bamfield', 'Alan Fitzgerald', 'Alan Moreau', 'Alana Goldstein', 'Aldo Campana', 'Alec Flynn', 'Alex Babbitt', 'Alex Castagne', 'Alex Dragicevich',
  'Alex Edelman', 'Alex English', 'Alex Gardes', 'Alex Gorge', 'Alex Hooper', 'Alex Kim', 'Alex Kumin', 'Alex Murdoch', 'Alex Pavone', 'Alex Pischera',
  'Alex Portillo', 'Alex Ptak', 'Alex Quow', 'Alexandria Curtwright', 'Alexis Bradby', 'Alexis Carabano', 'Alexis Guerreros', 'Alfred Kainga', 'Alfred Robles', 'Ali Drapos',
  'Ali Kolbert', 'Ali Macofsky', 'Ali Mehedi', 'Ali O''Neil', 'Ali Sultan', 'Ali Wong', 'Alia Bajorek', 'Alia Janine', 'Alingon Mitra', 'Alison Leiby',
  'Allan Havey', 'Allie Arasi', 'Allie Lawrence', 'Allie Mae', 'Allie Pearse', 'Allie Zisfein', 'Allison O''Conor', 'Ally Leftridge', 'Alon Elian', 'Alvin Kuai',
  'Alyce Chan', 'Alysia Hush', 'Amanda Alvich', 'Amanda Gail', 'Amanda Nettboy', 'Amanda Vasco', 'Amando Houser', 'Amber Autry', 'Amber Ruffin', 'Amber Singletary',
  'Amelia Ritthaler', 'Aminah Imani', 'Amy Cardinale', 'Amy Liszka', 'Amy Shanker', 'Andre D. Thompson', 'Andre Kim', 'Andre Myrie', 'Andre de Freitas', 'Andrea Jin',
  'Andrea Jones-Rooy', 'Andres Mallipudi', 'Andrew Casertano', 'Andrew Collin', 'Andrew Dismukes', 'Andrew Ferrara', 'Andrew Ginsberg', 'Andrew Manning', 'Andrew Michaan', 'Andrew Packer',
  'Andrew Santino', 'Andrew Schiavone', 'Andrew Schulz', 'Andy Aluise', 'Andy Fiori', 'Andy Haynes', 'Angelo Colina', 'Anna Bianco', 'Anna Roisman', 'Annabel Meschke',
  'Annick Adelle', 'Annie Lederman', 'Annie Russell', 'Anthony Cumia', 'Anthony DeVito', 'Anthony Jeselnik', 'Anthony Moore', 'Anthony Robustiano', 'Anthony Rodia', 'Anthony Vines',
  'Antonio Sanint', 'Aparna Nancherla', 'April Boddie', 'April Clark', 'Arden Myrin', 'Ardie Fuqua', 'Ari Shaffir', 'Ariana Speight', 'Ariel Elias', 'Ariel Evans',
  'Aries Spears', 'Asad Benbow', 'Ash Diggs', 'Asha Ward', 'Ashley Austin Morris', 'Ashley Gavin', 'Ashley Gutermuth', 'Ashley Hamilton', 'Ashley Hesseltine', 'Ashley King',
  'Ashley Ray', 'Ashlynn Salzano', 'Ashton Womack', 'Atheer Yacoub', 'Atsuko Okatsuka', 'Atsushi Ogata', 'Audrey Mora', 'Austin Locke', 'Austin Nasso', 'Avery Pearson',
  'Avi Liberman', 'Avry Ross', 'Ayanna Dookie', 'Bailey Pope', 'Bassam Shawl', 'Becky Granger', 'Beecher', 'Ben Bankas', 'Ben DeMarco', 'Ben Fisher',
  'Ben Frank', 'Ben Kirschenbaum', 'Ben Miller', 'Ben Rosenfeld', 'Ben Warheit', 'Benny Feldman', 'Bert Kreischer', 'Beth Stelling', 'Bianca Cristovao', 'Bianca Parato',
  'Big Jay Oakerson', 'Big Mack', 'Bill Bellamy', 'Billy Hockman', 'Billy Prinsell', 'Billy Wayne Davis', 'Blair Dawson', 'Blake Freeman', 'Blake Rosier', 'Bo Ballew',
  'Bob DiBuono', 'Bob the Drag Queen', 'Bobby Condon', 'Bobby Lee', 'Bobby Sheehan', 'Bonnie McFarlane', 'Bowen Yang', 'Brad Trackman', 'Brandi Augustus', 'Brandi Roberts',
  'Brandie Posey', 'Brandon Barrera', 'Brandon Follick', 'Brandon Reaves', 'Brandon Trusso', 'Brandon Wardell', 'Breck Gordon', 'Brendan Donegan', 'Brendan Sagalow', 'Brendan Scannell',
  'Brent Birnbaum', 'Bret Ernst', 'Brett Cooper', 'Brett Dodenhoff', 'Brett Goldstein', 'Brett Singer', 'Brian Bahe', 'Brian Elberg', 'Brian Grossi', 'Brian Holtzman',
  'Brian Monarch', 'Brian Moses', 'Brian Parise', 'Brian Scolaro', 'Brian Scott McFadden', 'Brian Six', 'Brian Smight', 'Brian Sullivan', 'Bridget Foley', 'Bridget McGuire',
  'Britney Ledesma', 'Britt Migs', 'Brittany Brave', 'Brittany Cardwell', 'Brittany Carney', 'Brittany Ross', 'Bronston Jones', 'Bronwyn Isaac', 'Brooks Allison', 'Brooks Tawil',
  'Brooks Wheelan', 'Bruce Bruce', 'Bruce Gray', 'Bry Weltz', 'Bryan McKenna', 'Bryan Vogt-Nilsen', 'Bryan Vokey', 'Byron Austin', 'Byron Bowers', 'CJ Hunt',
  'Cab Washington', 'Cactus Tate', 'Caitlin Cook', 'Caitlin Dullea', 'Caitlin Durante', 'Caitlin Peluffo', 'Caitlin Reese', 'Calise Hawkins', 'Calvin Cato', 'Camden Garcia',
  'Cameron Esposito', 'Cameron Leedy', 'Camille Roberts', 'Can Can', 'Candyce Cook', 'Cansu Karabiyik', 'Carl Sonnefeld', 'Carla Johnston', 'Carlos Hernandez', 'Carlos Mencia',
  'Carlos Santos', 'Carly Ballerini', 'Carly Kane', 'Carly Polistina', 'Carmen Angelica', 'Carmen Christopher', 'Carmen Lagala', 'Carmen Lynch', 'Carol Zoccoli', 'Carole Montgomery',
  'Carolina Montesquieu', 'Caroline Baniewicz', 'Caroline Hanes', 'Caroline Rhea', 'Caroline Yost', 'Carolyn Castiglia', 'Carson Olshansky', 'Carter Hambley', 'Casey Balsham', 'Casey James Salengo',
  'Cassie Willson', 'Cassie Workman', 'Cat Cohen', 'Catherine Cowin', 'Celeste Yim', 'Cesh Reyes', 'Chad Daniels', 'Chandler Dean', 'Chanel Ali', 'Chanel Omari',
  'Charlene Kaye', 'Charles Greaves', 'Charles McBee', 'Charlie Bardey', 'Charlie Flynn', 'Chase DuRousseau', 'Che Durena', 'Chelsea Morgan', 'Chiara Montali', 'Chike Robinson',
  'Chingo Bling', 'Chloe Fimiano', 'Chloe Hilliard', 'Chloe LaBranche', 'Chloe Radcliffe', 'Chloe Troast', 'Chris Adams', 'Chris Barnes', 'Chris Brown', 'Chris Cafero',
  'Chris D''Elia', 'Chris Distefano', 'Chris Donahue', 'Chris Envy', 'Chris Estrada', 'Chris Faga', 'Chris Fleming', 'Chris Gethard', 'Chris Hamilton', 'Chris Horne',
  'Chris Keise', 'Chris Lamberth', 'Chris Metcalfe', 'Chris Millhouse', 'Chris Murphy', 'Chris Redd', 'Chris Reiter', 'Chris Riggins', 'Chris Scopo', 'Chris Spencer',
  'Chris Turner', 'Chrissie Mayr', 'Christi Chiello', 'Christian Finnegan', 'Christian Johnson', 'Christian Weckesser', 'Christiana Jackson', 'Christina Walkinshaw', 'Christine Berg', 'Christine Carolyn',
  'Christopher James', 'Christy Miller', 'Chuck Nice', 'Cigi Farmer', 'Cipha Sounds', 'Claire Siemietkowski', 'Clare O''Kane', 'Clayton Fletcher', 'Clint Coley', 'Clyde Mack',
  'Cody Lewis', 'Cody Marino', 'Cole Cosby', 'Colin Armstrong', 'Colin Quinn', 'Colleen Genevieve', 'Collin Chamberlin', 'Colum Tyrrell', 'Concrete', 'Conner O’Malley',
  'Connor Dixon', 'Connor Meade', 'Conor Janda', 'Cooper Kim', 'Corey Holcomb', 'Corey Popowski', 'Corey Tindall', 'Corey Yoskowitz', 'Corinne Fisher', 'Correy Bell',
  'Cort McCown', 'Cortez Macklin', 'Cory Kahaney', 'Cory Peter Lane', 'Courtney Bee', 'Courtney Fearrington', 'Courtney Maginnis', 'Courtney O''Donnell', 'Courtney Pauroso', 'Craig Conant',
  'Craig Gass', 'Craig Robinson', 'Craig Shoemaker', 'Crenshaw White', 'Crickette Gill', 'Cris Sosa', 'Cristian Duran', 'Cynthia Kaplan', 'D''Arcy Carden', 'D. Lo',
  'D.L. Hughley', 'DC Benny', 'DC Youngfly', 'Daddy', 'Dale Elliott Jr.', 'Damien Lemon', 'Damien Speranza', 'Dan Altano', 'Dan Barry', 'Dan Carney',
  'Dan Chamberlain', 'Dan Davies', 'Dan Geneen', 'Dan LaMorte', 'Dan Licata', 'Dan Mintz', 'Dan Naturman', 'Dan Perlman', 'Dan Pulzello', 'Dan Rosen',
  'Dan Soder', 'Dan St. Germain', 'Dan Toomey', 'Dan Wickes', 'Dan Yang', 'Danette Rodriguez', 'Dani Lyle', 'Dani Riedel', 'Daniel J Perafan', 'Daniel Simonsen',
  'Daniel Storrow', 'Daniel Tirado', 'Daniela Mora', 'Danielle Clarke Fisher', 'Danielle Perez', 'Danish Maqbool', 'Danny DelColle', 'Danny Hurwitz', 'Danny Martinello', 'Danny Palmer',
  'Danny Polishchuk', 'Danny Sellers', 'Danny Suggs', 'Dante Nero', 'Daphnique Springs', 'Dara Jemmott', 'Darius Dinkins', 'Darren Brand', 'Darren Carter', 'Darren Knight',
  'Daryn Passarello', 'Dave Attell', 'Dave Columbo', 'Dave Hill', 'Dave Kinney', 'Dave Landau', 'Dave Lester', 'Dave Neal', 'Dave Ross', 'Dave Sirus',
  'Dave Smith', 'Dave Temple', 'David Cross', 'David Drake', 'David Jin', 'David Koechner', 'David Mills', 'David Nihill', 'David Piccolomini', 'David Roth',
  'David Spade', 'Dayton Bissett', 'DeAnne Smith', 'DeRay Davis', 'Dean David', 'Dean Delray', 'Dean Edwards', 'Dean Napolitano', 'Debra DiGiovanni', 'Delaney Rowe',
  'Deleta Hodges', 'Demetrius Fields', 'Demi Adejuyigbe', 'Denise Taylor', 'Deon Cole', 'Derek Drescher', 'Derek Gaines', 'Derek Humphrey', 'Derick Gonzalez', 'Derrick Brown',
  'Derrick Gonzalez', 'Derrick Stroup', 'Des Bishop', 'Desi Johnson', 'Devon Walker', 'Devyn Perry', 'Dewayne Perkins', 'Diana Aydin', 'Dina Hashem', 'Diona Doherty',
  'Divya Gunasekaran', 'DoKnow', 'Doctor Brown', 'Dominic Leonelli', 'Dominique Nisperos', 'Donna Lewis', 'Donnell Rawlings', 'Donwill', 'Doogie Horner', 'Dorian Debose',
  'Doug Smith', 'Doug Uram', 'Douglas Goodhart', 'Dov Davidoff', 'Drew Anderson', 'Drew Beekler', 'Drew Dunn', 'Drew Michael', 'Drew Tessier', 'Drew Thomas',
  'Drexton Clemons', 'Dru Montana', 'Dustin Nickerson', 'Dwayne Paul Cullen', 'Dylan Adler', 'Dylan Marron', 'Dylan O’Keeffe', 'Dylan Palladino', 'Dylan Sullivan', 'EJ Speaks',
  'Eagle Witt', 'Earthquake', 'Ed Bassmaster', 'Ed McGowan', 'Ed Rodriguez', 'Eddie Brill', 'Eddie Liles', 'Eddie Morrison', 'Eddie Pepitone', 'Edson Montenegro',
  'Edward Farrell', 'Edy Modica', 'Eion Falance', 'Eitan Levine', 'Eleanor Kerrigan', 'Electra Telesford', 'Elena Gabrielle', 'Eli Trichon', 'Eli Waithe', 'Eli Yudin',
  'Eliot Thompson', 'Elizabeth Pilar', 'Elizardi Castro', 'Ella Yurman', 'Elle Orlando', 'Ellen Harrold', 'Elon Altman', 'Ely Kreimendahl', 'Elyssa Phillips', 'Emil Wakim',
  'Emily Azrael', 'Emily Walsh', 'Emily Wilson', 'Emma Dalenberg', 'Emma Rogers', 'Emma Willmann', 'Emmy Blotnick', 'Eric Asker', 'Eric D’Alessandro', 'Eric Eaton',
  'Eric Menzel', 'Eric Neumann', 'Eric Walsh', 'Erica Rhodes', 'Erica Spera', 'Erik Bergstrom', 'Erik Bransteen', 'Erik Martini', 'Erik Scott', 'Erik Terrell',
  'Erin Jackson', 'Erin Keif', 'Erin Maguire', 'Espi Rivadeneira', 'Ester Steinberg', 'Esther Chen', 'Esther Fallick', 'Esther Povitsky', 'Ethan Mead', 'Ethan Simmons-Patterson',
  'Eugene Mirman', 'Eva Evans', 'Eva Nemiroff', 'Evan Altshuler', 'Evan Forde Barden', 'Fabrizio Copano', 'Faizon Love', 'Fallon Boles', 'Fareeha Khan', 'Farooq Hussain',
  'Farzin Moradi', 'Felicia Madison', 'Felipe Esparza', 'Fenelon Guillaume', 'Feraz Shere', 'Finesse Mitchell', 'Fiona Cauley', 'Fonzo Crow', 'Forrest Shaw', 'Francesco De Carlo',
  'Francis Ellis', 'Francis Foster', 'Francisco Ramos', 'Frank Caliendo', 'Frank Spadone', 'Frankie Benz', 'Frankie Quinones', 'Freddie Shanel', 'Freddy G', 'Freddy Sheffield',
  'Fumi Abe', 'Funny Marco', 'Gabby Bryan', 'Gabby Gutierrez-Reed', 'Gabby Jordan Brown', 'Gabe Dorado', 'Gabe Mollica', 'Gabe Pacheco', 'Gabriel Rutledge', 'Garrett Williams',
  'Gary Cannon', 'Gary G Garcia', 'Gary Gulman', 'Gary Owen', 'Gary Simons', 'Gary Vider', 'Gaspare Randazzo', 'Gastor Almonte', 'Gavin Matts', 'Gene Getman',
  'Geneva Rust-Orta', 'Geno Bisconte', 'Geo Yankey', 'Geoffrey Asmus', 'George Civeris', 'George Perez', 'Gianmarco Soresi', 'Gibran Saleem', 'Gigi Klein', 'Gina Brillon',
  'Gina Hyena', 'Gina Yashere', 'Ginny Hogan', 'Giulio Gallarotti', 'Glennis LaRoe', 'Glorelys Mora', 'Godfrey', 'Gonzo Leon', 'Gordon Baker Bone', 'Grace Bahler',
  'Grace Freud', 'Grace Johnson', 'Grace Leishman', 'Grace O’Malley', 'Grace Reiter', 'Gracie Canaan', 'Graham Cooper', 'Graham Kay', 'Grant Moore', 'Granville Bazemore',
  'Gray West', 'Greer Barnes', 'Greg Fitzsimmons', 'Greg Stone', 'Greg Warren', 'Greg Wilson', 'Gregg Rogell', 'Gregory Hoffman', 'Gus Constantellis', 'Gus Tate',
  'Guy Knoll', 'Guy Torry', 'Gwynn Factor', 'H. Foley', 'Haitian V', 'Haley Dercher', 'Haley Stiel', 'Hanna Dickinson', 'Hannah Berner', 'Hannah Lieberman',
  'Hari Kondabolu', 'Harper-Rose Drummond', 'Harris Alterman', 'Harris Stanton', 'Harrison Greenbaum', 'Harry Settel', 'Harry Terjanian', 'Harshil Shukla', 'Hassan Phills', 'Hayden Arrington',
  'Hayden Johnson', 'Heather Shaw', 'Heavvy', 'Heidi Grandberry', 'Helen K.', 'Heming Ge', 'Henry Sir', 'Holmes', 'Hoodo Hersi', 'Hooter Moreno',
  'Iain Stirling', 'Ian Bagg', 'Ian Fidance', 'Ian Lara', 'Ian Levy', 'Ian Lockwood', 'Ibhan Kulkarni', 'Ibrahim Khalif', 'Igor Martinez', 'Ike Ufomadu',
  'Indi Remy', 'Indigo Asim', 'Irene Morales', 'Irene Tu', 'Irina Chelidze', 'Isa Medina', 'Isaac Gartenberg', 'Isabel Hagen', 'Ishmael Gaynor', 'Isiah Kelly',
  'Ismael Loutfi', 'Ivi Demi', 'Ivy Wolk', 'J Smitty', 'J. Valentino', 'J.P. McDade', 'JC Mendoza', 'JJ Liberman', 'JJ Mattise', 'JJ Williamson',
  'JR De Guzman', 'Ja-Ron Young', 'Jaboukie Young-White', 'Jack Assadourian Jr.', 'Jack Bensinger', 'Jack Finnegan', 'Jack Shaw', 'Jackie Fabulous', 'Jaclyn Lore-Edwards', 'Jacob Williams',
  'Jacqueline Blizzard', 'Jacquis Neal', 'Jad Sleiman', 'Jade Catta-Preta', 'Jaffer Khan', 'Jake Cornell', 'Jake Silberman', 'Jake Velazquez', 'Jake Vevera', 'Jamario McClain',
  'James Austin Johnson', 'James Camacho', 'James Goff', 'James Hamilton', 'James Mattern', 'James Mwaura', 'James Pontillo', 'Jamie Kilstein', 'Jamie Lee', 'Jamie Linn Watson',
  'Jamie Wolf', 'Jane Condon', 'Janeane Garofalo', 'Janelle Draper', 'Janelle James', 'Janice Maffei', 'Janine Harouni', 'Jared Freid', 'Jared Goldstein', 'Jared Harvin',
  'Jared Schwartz', 'Jared Waters', 'Jarrett Campbell', 'Jason Chatfield', 'Jason Cheny', 'Jason Choi', 'Jason Salmon', 'Jatty Robinson', 'Jay Castillo', 'Jay Jurden',
  'Jay Larson', 'Jay Pharoah', 'Jay Washington', 'Jaye McBride', 'Jeaux King', 'Jeff Allen', 'Jeff Arcuri', 'Jeff Cerulli', 'Jeff Dylan', 'Jeff Garlin',
  'Jeff Hiller', 'Jeff Lawrence', 'Jeff Leach', 'Jeff Maurer', 'Jeff Scheen', 'Jeff Wittek', 'Jeff Wright', 'Jeffrey Baldinger', 'Jen Amo', 'Jen Murphy',
  'Jena Friedman', 'Jenae Boston', 'Jenelle Jackson', 'Jenn Lederer', 'Jenn Madden', 'Jenn Sterger', 'Jenny Arimoto', 'Jenny Gorelick', 'Jenny Hagel', 'Jenny Saldana',
  'Jenny Zigrino', 'Jeremiah Watkins', 'Jeremy Piven', 'Jeremy Schaftel', 'Jeremyah Schur', 'Jerrod Carmichael', 'Jerry Garcia', 'Jerry Rocha', 'Jerry Trainor', 'Jess Elgene',
  'Jess Hilarious', 'Jess Salomon', 'Jesse Eigner', 'Jesse Singal', 'Jesse Townsend', 'Jesse Warren', 'Jessica Frey', 'Jessica Kirson', 'Jessica Levin', 'Jessie Lee',
  'Jessy Morner-Ritt', 'Jesus Sepulveda', 'Jiaoying Summers', 'Jilberto Soto', 'Jill Gonzalez', 'Jill Weiner', 'Jim Dailakis', 'Jim Flannigan', 'Jim Florentine', 'Jim Norton',
  'Jim Search', 'Jim Tews', 'Jimmy Failla', 'Jimmy McMurrin', 'Jimmy Pardo', 'Jo Firestone', 'Joan Glackin', 'Joanna M. Briley', 'Joanne Filan', 'Joanne McNally',
  'Joe Bartnick', 'Joe Briggs', 'Joe Castle Baker', 'Joe DeRosa', 'Joe DeVito', 'Joe Gorman', 'Joe Larson', 'Joe List', 'Joe Machi', 'Joe Mahoney',
  'Joe Mande', 'Joe Nunnink', 'Joe Opio', 'Joe Pera', 'Joe Russell', 'Joe Sib', 'Joe Wong', 'Joe Zimmerman', 'Joey Avery', 'Joey Callahan',
  'Joey Dardano', 'Joey Hamburger', 'Joey Vega', 'John Bishop', 'John Campanelli', 'John Franklin', 'John Fugelsang', 'John Goblikon', 'John Hedrick', 'John Joseph',
  'John Kennedy', 'John Lutz', 'John Moses', 'John Patrick Coan', 'John Pizzi', 'John Sikie', 'Johnny Mitchell', 'Johnny Watson', 'Jon Alcabes', 'Jon Bramnick',
  'Jon Fisch', 'Jon Lajoie', 'Jon Laster', 'Jon Rudnitsky', 'Jon Tut', 'Jonas Jeannot', 'Jonathan Randall', 'Jonathan Tillson', 'Jonathan Van Ness', 'Jonathan van Halem',
  'Jonnea Herman', 'Jordan Carlos', 'Jordan Coley', 'Jordan Jensen', 'Jordan Perry', 'Jordan Rock', 'Jordan Savusa', 'Jordon Ferber', 'Joseph Lymous', 'Joseph Rosenzweig',
  'Josh Adam Meyers', 'Josh Alba', 'Josh Blue', 'Josh Gondelman', 'Josh Johnson', 'Josh Nasser', 'Josh Ri''Esgo', 'Josh Sharp', 'Josh Simensky', 'Joshua Lampley',
  'Jourdain Fisher', 'Joyelle Nicole Johnson', 'Juan Nicolon', 'Judah Friedlander', 'Judge Miles', 'Judy Gold', 'Juju Fevry', 'Jules Posner', 'Julia Desmond', 'Julia Dicesare',
  'Julia Kastner', 'Julia Leahy', 'Julia Shiplett', 'Julia Wendt', 'Julian Breheny', 'Julian McCullough', 'Juliana Rodrigues', 'Julie Kim', 'Julie Lim', 'Julio Diaz',
  'Just Nesh', 'Justin Catchens', 'Justin Martindale', 'Justin Silva', 'Justin Silver', 'Justine Marino', 'KC Shornima', 'Kaneez Surka', 'Kareem Green', 'Karen Bergreen',
  'Karen Mills', 'Karla Watkins', 'Karli Marulli', 'Karolena Theresa', 'Kasaun Wilson', 'Kase Raso', 'Kat Belinfante', 'Kat Holmes', 'Kat Radley', 'Kate Lavrentios',
  'Kate Nichols', 'Kate Sisk', 'Kate Willett', 'Kate Wolff', 'Katherine Blanford', 'Katherine Gorham', 'Katie Blunt', 'Katie Boyle', 'Katie Finn', 'Katie Haller',
  'Katie Hannigan', 'Katie Heneghan', 'Katrina Davis', 'Kaye Loggins', 'Keara Sullivan', 'Keegan Tindall', 'Keith Alberstadt', 'Keith Johnson', 'Keith Robinson', 'Kel Cripe',
  'Kel Perez', 'Kellan Breen', 'Kelly Bachman', 'Kelly Cooper', 'Kelly McInerney', 'Kelly Taylor', 'Kelsey Cook', 'Kendall Farrell', 'Kendra Cunningham', 'Kenice Mobley',
  'Kenny Warren', 'Kenyon Adamcik', 'Keren Margolis', 'Kerri Louise', 'Kerryn Feehan', 'Kev Herrera', 'Kevin Bartini', 'Kevin Casey White', 'Kevin Dombrowski', 'Kevin Hurley',
  'Kevin Iso', 'Kevin James Thornton', 'Kevin McCaffrey', 'Kevin Mulharin', 'Kevin Nealon', 'Kevin Ryan', 'Kevin Sullivan', 'Kim Congdon', 'Kimberly Dinaro', 'Kira Soltanovich',
  'Kiran Deol', 'Kitty Reynolds', 'Kofi Thomas', 'Kountry Wayne', 'Krissy Gregory', 'Kristal Adams', 'Kristen Carney', 'Kristen Toomey', 'Kristin Chirico', 'Krystyna Hutchinson',
  'Kunal C. Arora', 'Kyle Ayers', 'Kyle Dunnigan', 'Kyle Gillis', 'Kyle Gordon', 'Kyle Lewis', 'Kyle Marian', 'Kyle Vaters', 'Kylie Brakeman', 'La Chupitos',
  'Lana Schwartz', 'Lana Siebel', 'Lance Weiss', 'Larry Beyah', 'Larry Dorsey Jr', 'Laura Bolivar', 'Laura High', 'Laura Merli', 'Laura Michelle', 'Laura Peek',
  'Laura Sogar', 'Lauren Hope Krass', 'Lauren Servideo', 'Laurie Kilmartin', 'Lavell Crawford', 'Lawrence Reese', 'Laz Rivero', 'LeClerc Andre', 'Leah Lamarr', 'Leah Rudick',
  'Lea’h Sampson', 'Lee Syatt', 'Lee Valentin', 'Leighann Lord', 'Leland Long', 'Lenny Marcus', 'Leo Rojas', 'Leonard Ouzts', 'Leslie Jones', 'Leslie Liao',
  'Lev Fer', 'Levi White', 'Lewis Belt', 'Liam Dalton', 'Liam Kyle Sullivan', 'Liam Nelson', 'Lil'' Mo Mozzarella', 'Lili Michelle', 'Lily Armstrong', 'Lily Lester',
  'Lindsay Theisen', 'Lindsey Barnes', 'Linette Palladino', 'Linnea Sage', 'Lisa Albano', 'Lisa Curry', 'Lisa Marie', 'Lissa Lenis', 'Liv Talley', 'Liz Barrett',
  'Liz Glazer', 'Liz Miele', 'Liza Treyger', 'Lizzy Cassidy', 'Logan Guntzelman', 'Logan Malin', 'Lois Thompson', 'London Brown', 'Loni Love', 'Lotto Marie',
  'Louis Katz', 'Luca Ferro', 'Lucas Connolly', 'Lucas O''Neil', 'Lucas Stone', 'Lucas Zelnick', 'Lucie Pohl', 'Luis De Alba', 'Luis J. Gomez', 'Luis Lopez',
  'Luisa Lange', 'Luisa Omielan', 'Lukas Arnold', 'Luke Kidgell', 'Luke Mones', 'Luke Thayer', 'Luke Touma', 'Lynn Maleh', 'Lynne Koplitz', 'Lyrix',
  'Mac O’Hara', 'Macario Brujo', 'Macy Kwok', 'Maddie Peck', 'Maddie Wiener', 'Maddy Kelly', 'Maddy Smith', 'Madeleine Rowe', 'Madi Hart', 'Madison Malloy',
  'Mae Planert', 'Maggie Crane', 'Maggie Lalley', 'Maggie Naughton', 'Maggie Olmsted', 'Maggie Winters', 'Mahesh Kotagi', 'Makael Exum', 'Mal Hall', 'Malia Simon',
  'Malik Elassal', 'Malika Sen', 'Malorie Bryant', 'Mandal', 'Manolo Moreno', 'Marc Gerber', 'Marc Henderson', 'Marc Theobald', 'Marcello Hernandez', 'Marcia Belsky',
  'Marcus Monroe', 'Margaret Cho', 'Maria DeCotis', 'Maria Heinegg', 'Marie Faustin', 'Mariel Jimenez', 'Marina Franklin', 'Mario Adrion', 'Mario Salazar', 'Marion Grodin',
  'Marito Lopez', 'Mark Curry', 'Mark Gagnon', 'Mark Gregory', 'Mark Hayes', 'Mark Little', 'Mark Normand', 'Mark Riccadonna', 'Mark Viera', 'Marlon Wayans',
  'Marshall Brandon', 'Martin Amini', 'Martin Moreno', 'Martin Phillips', 'Martin Urbano', 'Marty Miller', 'Mary Beth Barone', 'Mary Houlihan', 'Mary Lynn Rajskub', 'Mary Neely',
  'Mary Santora', 'Masood Boomgaard', 'Matt Barats', 'Matt Benjamin', 'Matt Bowman', 'Matt Friend', 'Matt Fulchiron', 'Matt Goldich', 'Matt Koff', 'Matt Lopes',
  'Matt Maran', 'Matt McCoy', 'Matt Pavich', 'Matt Richards', 'Matt Rogers', 'Matt Ruby', 'Matt Somerstein', 'Matt Wayne', 'Matteo Lane', 'Matthew Broussard',
  'Matty Chymbor', 'Matty Litwack', 'Maureen Langan', 'Maurice Benard', 'Max Antonucci', 'Max Fine', 'Max Gross', 'Max Higgins', 'Max Manticof', 'Max Moacanin',
  'Max Wittert', 'Maximilian Spinelli', 'Maya Sharma', 'Maya Swift', 'Maz Jobrani', 'McKenna Moore', 'Meelah Dee', 'Meg Chizek', 'Meghan Hanley', 'Meghan Walsh',
  'Mehran Khaghani', 'Meka Mo', 'Melissa Diaz', 'Melissa Villasenor', 'Meno Fernandez', 'Menuhin Hart', 'Meredith Dietz', 'Meshelle “The Indie Mom of Comedy”', 'Mia Jackson', 'Mia Wilson',
  'Mic Nguyen', 'Michael Abber', 'Michael Albanese', 'Michael Blackson', 'Michael Blaustein', 'Michael Brigante', 'Michael Che', 'Michael Cruz Kayne', 'Michael Good', 'Michael Harrison',
  'Michael Hirsch', 'Michael Kosta', 'Michael Larkin', 'Michael Lenoci', 'Michael Loftus', 'Michael Longfellow', 'Michael Magid', 'Michael Palascak', 'Michael Rapaport', 'Michael Rowland',
  'Michael Somerville', 'Michael Turner', 'Michael Yo', 'Michele Durante', 'Michelladonna', 'Michelle Buteau', 'Michelle Wolf', 'Mick Foley', 'Mick Thomas', 'Mika Stein',
  'Mike Bramante', 'Mike Britt', 'Mike Cannon', 'Mike Drucker', 'Mike Eaton', 'Mike Falzone', 'Mike Feeney', 'Mike Figs', 'Mike Fine', 'Mike Finoia',
  'Mike Hanford', 'Mike King', 'Mike McPartland', 'Mike Recine', 'Mike Stanley', 'Mike Toohey', 'Mike Vecchione', 'Mike Yard', 'Mikey Greenblatt', 'Mila Knockabitch',
  'Mila Myles', 'Milly Tamarez', 'Mina Hartong', 'Misha Han', 'Miss Jones', 'Miss Lissa', 'Missy McIntosh', 'Mo Hill', 'Mo Mandel', 'Modi',
  'Moe Yaqub', 'Mohanad Elshieky', 'Molly Brenner', 'Molly Densmore', 'Molly Kearney', 'Molly Kornfeld', 'Monique Latise', 'Monroe Martin', 'Monty Franklin', 'Moody McCarthy',
  'Moonie', 'Moses Storm', 'Moss Perricone', 'Mouse Jones', 'Ms. Poundcake', 'Murahd Shawki', 'Mustafe Mussa', 'Myka Fox', 'Myq Kaplan', 'Mz. Sin',
  'Nacho Redondo', 'Nancy Giles', 'Naomi Karavani', 'Napoleon Emill', 'Nat Badillo', 'Natalia De Los Santos', 'Natalie Cuomo', 'Natalie Friedman', 'Natalie Rotter-Laitman', 'Nataly Aukar',
  'Natan Badalov', 'Natasha Mercado', 'Natasha Vaynblat', 'Nate Meeker', 'Nathan Habib', 'Nathan Macintosh', 'Na’im Ali', 'Neel Ghosh', 'Neema Naz', 'Neil Rubenstein',
  'Neko White', 'Nell Kessler', 'Nic Dundas', 'Nick Callas', 'Nick Griffin', 'Nick Guercio', 'Nick Guerra', 'Nick Hopping', 'Nick Murphy', 'Nick Naney',
  'Nick Simmons', 'Nick Smith', 'Nick Thune', 'Nick Tilleli', 'Nick Viagas', 'Nicky Paris', 'Nicky Sunshine', 'Nico Carney', 'Nico Cattaneo', 'Nikhil Mehta',
  'Nikki MacCallum', 'Nina Barnett', 'Nina Kharoufeh', 'Nina Nguyen', 'Nina Tarr', 'Nish Kumar', 'Noah Findling', 'Noah Gardenswartz', 'Noah Miller', 'Noah Savage',
  'Noah Snyder', 'Noam Shuster-Eliassi', 'Noel Leon', 'Noel Miller', 'Nonye Brown-West', 'Norah Yahya', 'Nore Davis', 'Nori Reed', 'Norlex Belma', 'Nurse John',
  'Olga Namer', 'Olivia Barbulescu', 'Olivia Carter', 'Olivia Levine', 'Omar Gooding', 'Omar Jenkins', 'Onika McLean', 'Ontonio Kareem', 'Ophira Eisenberg', 'Oscar Aydin',
  'Oscar Collazos', 'Owen Smith', 'PJ Landers', 'Pamela Schuller', 'Paris Sashay', 'Parker Callahan', 'Pat Barker', 'Pat Brown', 'Pat Burtscher', 'Pat Byrne',
  'Patrice DeVeaux', 'Patricia Dinglasan', 'Patrick Doran', 'Patrick Holbert', 'Patrick Warburton', 'Paul Elia', 'Paul Mecurio', 'Paul Valdez Rodriguez', 'Paul Varghese', 'Paul Virzi',
  'Paula J. Leon', 'Paulina Luke', 'Pedro Gonzalez', 'Peet Guercio', 'Peng Dang', 'Perry Strong', 'Pete Holmes', 'Pete Lee', 'Peter Antoniou', 'Peter Grosz',
  'Peter Guarraci', 'Peter James Fowler', 'Peter Murphy', 'Peter Revello', 'Peter Wong', 'Petey DeAbreu', 'Peyton Dix', 'Phil Duckett', 'Phil Hanley', 'Phil Hunt',
  'Phil Medina', 'Phil Morris', 'Phoebe Robinson', 'Piers Moreton', 'Pinky Patel', 'Pooja Reddy', 'Pranav Behari', 'Priya Blunts', 'Punkie Johnson', 'Quinton Jones',
  'RJ Prince', 'Raanan Hershberg', 'Rachel Coster', 'Rachel Darvas', 'Rachel Feinstein', 'Rachel Green', 'Rachel Kaly', 'Rachel Lenihan', 'Rachel McCartney', 'Rachel Pegram',
  'Rachel Scanlon', 'Rachel Williams', 'Rachel Wolfson', 'Rae Sanni', 'Rafi Bastos', 'Rahul Pandya', 'Raina Morris', 'Raj Suresh', 'Rallo Boykins', 'Ralph Anthony',
  'Ralph Barbosa', 'Ramsey Badawi', 'Ramy Youssef', 'Raul Sanchez', 'Ray Badran', 'Ray Devito', 'Ray Ellin', 'Ray Gootz', 'Ray Zawodni', 'Rebecca Kaplan',
  'Rebecca Reingold', 'Rebecca Weiser', 'Reece Muniz', 'Reem Edan', 'Reg Thomas', 'Reggie Conquest', 'Reggie Kush', 'Regina DeCicco', 'Reid Pope', 'Rell Battle',
  'Remy Kassimir', 'Rhonda Hansome', 'Rhys Darby', 'Ria Lina', 'Rich Aronovitch', 'Rich Francese', 'Rich Vos', 'Richard Perez', 'Richie Redding', 'Rick Crom',
  'Rick Younger', 'Rickey Smiley', 'Rickisa Owens', 'Ricky Velez', 'Riley Lassin', 'Rima Parikh', 'Rishi Arya', 'Ritu Tirthani', 'Rivest Dunlap', 'Riylan Mills',
  'Rob Cantrell', 'Rob Haze', 'Rob Kazi', 'Rob Ryan', 'Robby Collins', 'Robby Hoffman', 'Robby Slowik', 'Robert Johnson', 'Robert Kelly', 'Robert Morgan',
  'Rochée Jeffrey', 'Rocky Dale Davis', 'Rod O''Toole', 'Roddy MacInnes', 'Roey Rozen', 'Rojo Perez', 'Romy Rosner', 'Ron Bennington', 'Ron Nobles', 'Roni Shanell',
  'Ronnie Lordi', 'Ronnie Smith', 'Ronny Chieng', 'Rory Scovel', 'Rose Kelso', 'Rosebud Baker', 'Rosey Catherine', 'Roy Wood Jr.', 'Rufat Agayev', 'Ruperto Vanderpool',
  'Russell Daniels', 'Russell Peters', 'Ryan Beck', 'Ryan Ciecwisz', 'Ryan Donahue', 'Ryan Erwin', 'Ryan Goodcase', 'Ryan Hamilton', 'Ryan Long', 'Ryan Reiss',
  'Ryan Shaner', 'Ryan Thomas', 'Sabeen Sadiq', 'Sabina Meschke', 'Sabrina Brier', 'Sabrina Jalees', 'Sabrina Wu', 'Sahib Singh', 'Saidah Belo-Osagie', 'Sally Ann Hall',
  'Salma Hindy', 'Salma Zaky', 'Sam Clark', 'Sam Corbin', 'Sam Evans', 'Sam Frank', 'Sam Jay', 'Sam Morril', 'Sam Morrison', 'Sam Roberts',
  'Sam Rogal', 'Sam Rubinoff', 'Sam Schaefer', 'Sam Taggart', 'Sam Tallent', 'Samantha Ruddy', 'Samantha Santos', 'Sami Schwaeber', 'Sammy Obeid', 'Samson Crouppen',
  'Sandeep Sen', 'Sandi Benton', 'Santi Espinosa', 'Santiago Angel', 'Sara Bergmark', 'Sara Hennessey', 'Sara Huntington', 'Sara Weinshenk', 'Sarah Adelman', 'Sarah Bell',
  'Sarah Cooper', 'Sarah Hartshorne', 'Sarah Hennessey', 'Sarah Sherman', 'Sarah Tollemache', 'Sasha Merci', 'Sasha Srbulj', 'Savannah DesOrmeaux', 'Savannah Pagnozzi', 'Sean Conrad',
  'Sean Donnelly', 'Sean Harper', 'Sean Hegarty', 'Sean Millea', 'Sean Mullins', 'Sean Patton', 'Sean Reilly', 'Seaton Smith', 'Sergio Chicon', 'Seth Herzog',
  'Shafi Hossain', 'Shalewa Sharpe', 'Shan Fahey', 'Shane Bianchi', 'Shane O’Connor', 'Shane Todd', 'Shane Torres', 'Shang', 'Shannon Fiedler', 'Shapel Lacey',
  'Shari Diaz', 'Sharief Johnson', 'Sharon Simon', 'Shatara Curry', 'Shaun Murphy', 'Shaunak Godkhindi', 'Shelly Belly', 'Shelly Christian', 'Shenuque Tissera', 'Sheria Mattis',
  'Shermelle Coleman', 'Sherrod Small', 'Shiraz Belblidia', 'Shivani Dave', 'Shounak Vale', 'Shuler King', 'Shyam Subramanian', 'Sibo McNally', 'Sienna Hubert-Ross', 'Sila Puhl',
  'Sima Sepehri', 'Simeon Goodson', 'Simon Bloch', 'Simon Fraser', 'Skye Grayson', 'Skyler Higley', 'Slater Harrison', 'Sommore', 'Sonia Denis', 'Sonya Vai',
  'Soo Ra', 'Sophia Wilson Pelton', 'Sophie Duker', 'Sophie Zucker', 'Spencer Sileo', 'Spencer Wright', 'Spike Einbinder', 'Srishti Sharma', 'Stavros Halkias', 'Stef Dag',
  'Steph Tolev', 'Stephanie Goldklang', 'Stephen Bolles', 'Stephon Hightower', 'Steve Byrne', 'Steve Furey', 'Steve Hofstetter', 'Steve Hytner', 'Steve Marshall', 'Steve Rannazzisi',
  'Steve Trevino', 'Steve-O', 'Steven Rogers', 'Stewart Fullerton', 'Stewie Vill', 'Stuttering John Melendez', 'Subhah Agarwal', 'Sue Costello', 'Sunny LaPrade', 'Sureni Weerasekera',
  'Susan Jeremy', 'Sydnee Washington', 'Sydney Duncan', 'T. Murph', 'T.J. Miller', 'TK Kirkland', 'Tahlia Robinson', 'Tait Winston', 'Talal Alyan', 'Talent Harris',
  'Talent Harris Jr.', 'Talia Reese', 'Talib Babb', 'Tallie Medel', 'Tanael Joachim', 'Tanner Riley', 'Tara Cannistraci', 'Tata Sherise', 'Tatiana Frank', 'Tawanda Gona',
  'Tayler Yarish', 'Taylor Garron', 'Taylor Ortega', 'Taylor Rogers', 'Taylor Williamson', 'Ted Alexandro', 'Ted Barton', 'Tej Khanna', 'Teresa DeGaetano', 'Terry McNeely',
  'Tess Tregellas', 'Tessa Belle', 'Thash Mose', 'That One Mailman', 'The Sklar Brothers', 'Theresa Moriarty', 'Tiago Santineli', 'Tiffanee Lee', 'Tiffany Anderson', 'Tiffany Haddish',
  'Tim Butterly', 'Tim Dillon', 'Tim Krompier', 'Tim Myer', 'Tim Platt', 'Tim Smith', 'Tina Friml', 'Tina Sieben', 'Tip Harris', 'Tish Hines',
  'Tisha Campbell', 'Tito Garza', 'Tobin Miller', 'Toby McMullen', 'Tocarra Elise', 'Tocarra Mallard', 'Todd Barry', 'Toler Wolfe', 'Tom Cassidy', 'Tom Cotter',
  'Tom Delgado', 'Tom Kelly', 'Tom McGuire', 'Tom Papa', 'Tom Thakkar', 'Tom Zappia', 'Tommy Bayer', 'Tommy Brennan', 'Tommy Davidson', 'Tommy McNamara',
  'Tonja D', 'Tony Baker', 'Tony Deyo', 'Tony Roberts', 'Tony Rock', 'Tony Sykowski', 'Tony Woods', 'Torey Cole', 'Toria Rainey', 'Torio Van Grol',
  'Tracey Carnazzo', 'Tracy McClendon', 'Travis Grant', 'Travis Holp', 'Travis Jay', 'Trevor Noah', 'Trevor Wallace', 'Trey Galyon', 'Trey Kennedy', 'Tristan Bowling',
  'Trixx', 'Troy Alan', 'Troy Bond', 'Tu Rae', 'Tucker Brookshire', 'Turner Sparks', 'Tyler Fischer', 'Tyler Groce', 'Tyler Horvath', 'Tyler Mead',
  'Tyler Rothrock', 'Tyrone Thornhill', 'Uly Morazan', 'Usama Siddiquee', 'Usama Siddiqui', 'Val Bodurtha', 'Valeria Vulpe', 'Vanessa Hollingshead', 'Vanetta Schoefield', 'Vannessa Jackson',
  'Venessa Peruda', 'Veronica Kwiatkowski', 'Veronica Mosey', 'Veronika Slowikowska', 'Vic DiBitetto', 'Victor Medina', 'Victor Tran', 'Vincent Bryant', 'Vincent James', 'Vinnie Brand',
  'Vinnie Corrales', 'Vinny Guadagnino', 'Vir Das', 'Virginia Dickens', 'Vishnu Vaka', 'Vivien Chen', 'Vladimir Caamano', 'Wali Collins', 'Wally Baram', 'Whitley Watson',
  'Whitney Chanel Clark', 'Wil Sylvince', 'Wilfred Padua', 'Will Abeles', 'Will Burkart', 'Will Foskey', 'Will Julian', 'Will Purpura', 'Willie Barcena', 'Willie Simon',
  'Wolfgang Hunter', 'Wyatt Feegrado', 'Yamaneika Saunders', 'Yannis Pappas', 'Yassir Lester', 'Yedoye Travis', 'Yemi Afolabi', 'Yohay Sponder', 'Yoshiko Watson', 'Young Tef',
  'Youngmi Mayer', 'Yvette Segan', 'Zach Braviette', 'Zach Brazao', 'Zach Gish', 'Zach McGovern', 'Zach Russell', 'Zach Sage Fox', 'Zach Schiffman', 'Zach Stein',
  'Zach Vandegrift', 'Zach Zimmerman', 'Zach Zucker', 'Zack DiDonato', 'Zack Signore', 'Zahid Dewji', 'Zainab Johnson', 'Zarna Garg', 'Zavior Phillips', 'Zeo Niu',
  'Zilla Vodnas', 'Zoe Levy', 'Zoltan Kaszas', 'Zubi Ahmed'
);
