export const PGLITE_TEST_FILES = [
    "app/api/admin/podcast-ownership-reviews/route.test.ts",
    "lib/data/home/getAffinityRails.test.ts",
    "lib/data/home/getFreshAndRisingRails.test.ts",
    "lib/data/home/getPodcastEpisodeDiscovery.test.ts",
    "lib/data/home/getTouringScarcityRails.test.ts",
    "lib/data/home/getTrendingComedians.test.ts",
    "lib/discovery/favoriteGrowth.test.ts",
    "lib/discovery/features.test.ts",
    "lib/discovery/railPolicyMigration.test.ts",
    "prisma/adminActionAudit.test.ts",
    "prisma/comedianVisibleConsolidation.test.ts",
    "prisma/discoveryEventsMigration.test.ts",
    "prisma/improvAsylumSourceMigration.test.ts",
    "prisma/podcastEpisodeUniqueRelease.test.ts",
    "prisma/podcastGraphMigration.test.ts",
    "prisma/podcastSlugMigration.test.ts",
    "prisma/schema.youtube-live-notifications.test.ts",
    "prisma/showMinPriceTrigger.test.ts",
    "prisma/showTicketsSoldOutTrigger.test.ts",
    "prisma/ticketPurchaseClickMigration.test.ts",
] as const;
