export enum EntityType {
    Comedian = "comedian",
    Club = "club",
    Show = "show",
    Tag = "tag",
    User = "user",
    UserProfile = "user_profile",
    Account = "account",
    Session = "session",
    VerificationToken = "verification_token",
    FavoriteComedian = "favorite_comedian",
    LineupItem = "lineup_item",
    TaggedClub = "tagged_club",
    TaggedComedian = "tagged_comedian",
    TaggedShow = "tagged_show",
}