
export enum SortParamValue {
    DateAsc = "date_asc",
    DateDesc = "date_desc",
    PriceAsc = "price_asc",
    PriceDesc = "price_desc",
    PopularityAsc = "popularity_asc",
    PopularityDesc = "popularity_desc",
    InstagramFollowersAsc = "instagram_followers_asc",
    InstagramFollowersDesc = "instagram_followers_desc",
    TiktokFollowersAsc = "tiktok_followers_asc",
    TiktokFollowersDesc = "tiktok_followers_desc",
    YoutubeFollowersAsc = "youtube_followers_asc",
    YoutubeFollowersDesc = "youtube_followers_desc",
    TotalShowsAsc = "total_shows_asc",
    TotalShowsDesc = "total_shows_desc",
    SoldOutShowsAsc = "sold_out_shows_asc",
    SoldOutShowsDesc = "sold_out_shows_desc",
    SoldOutAsc = "sold_out_asc",
    SoldOutDesc = "sold_out_desc",
    RadiusAsc = "radius_asc",
    RadiusDesc = "radius_desc",
    StartDateAsc = "start_date_asc",
    StartDateDesc = "start_date_desc",
    EndDateAsc = "end_date_asc",
    EndDateDesc = "end_date_desc",
}

export const allSortOptions = [
    SortParamValue.DateAsc.valueOf(),
    SortParamValue.DateDesc.valueOf(),
    SortParamValue.PriceAsc.valueOf(),
    SortParamValue.PriceDesc.valueOf(),
    SortParamValue.PopularityAsc.valueOf(),
    SortParamValue.PopularityDesc.valueOf(),
    SortParamValue.InstagramFollowersAsc.valueOf(),
    SortParamValue.InstagramFollowersDesc.valueOf(),
    SortParamValue.TiktokFollowersAsc.valueOf(),
    SortParamValue.TiktokFollowersDesc.valueOf(),

]