-- TASK-3027: Google Places-backed club location backfill.
--
-- Generated by scripts/core/backfill_club_location_records_google_places_2026_06_20.py
-- on 2026-06-20, then hand-classified for the six rejected rows:
--   539  Kricket Comedy: Google Places top hit was Comedy Cellar (NY), but
--        DB shows prove Kricket is a multi-venue producer. Keep the row as a
--        visible aggregate/trigger for now so existing shows remain visible,
--        and stamp a production_companies row for attribution.
--   556  Coastal Entertainment Productions: existing place_id resolves to an
--        Astoria office, not a venue. Model as production company and keep the
--        hidden source row out of public club browse.
--   573  Big Pine Comedy Festival: no Google Places single-venue hit; current
--        schema intentionally models festivals as clubs.club_type='festival'.
--   620  Comedy Shows Near Me: Google Places top hit was Comedy Cellar; DB
--        shows prove this is a multi-venue aggregator with disabled source.
--   3007 MGM National Harbor: existing Google place_id resolves to the real
--        Maryland venue; old state=DC was wrong.
--   4036 Ticketmaster National: intentional hidden platform trigger, not a
--        public club.
--   8735 Address in Booking details: Eventbrite secret-location style record;
--        no public Google Places address is available.

CREATE TEMP TABLE club_location_google_places_backfill (
    club_id integer PRIMARY KEY,
    place_id text NOT NULL,
    address text NOT NULL,
    city text,
    state text,
    latitude double precision,
    longitude double precision,
    source text NOT NULL,
    rationale text NOT NULL
) ON COMMIT DROP;

INSERT INTO club_location_google_places_backfill (club_id, place_id, address, city, state, latitude, longitude, source, rationale)
VALUES
    (139, 'ChIJxUVIdcpRa4gR0nwaIVzRVMU', '10 W Georgia St, Indianapolis, IN 46225, USA', 'Indianapolis', 'IN', 39.7644091, -86.1584286, 'place_id', 'accepted from existing google_place_id'),
    (195, 'ChIJQT2D-MKBhYAR0qAObHcoxwo', '644 Broadway, San Francisco, CA 94133, USA', NULL, 'CA', 37.7980047, -122.4079241, 'text_search', 'accepted from text search with matching identity context'),
    (207, 'ChIJ-bBwwsStGYgR_brjZDHmeP4', '20 Monroe Ave NW #3f, Grand Rapids, MI 49503, USA', NULL, 'MI', 42.9636194, -85.6729333, 'text_search', 'accepted from text search with matching identity context'),
    (412, 'ChIJpVu0ZzPvwIkRlPwG8dwYVkQ', '1133 Boardwalk, Atlantic City, NJ 08401, USA', NULL, 'NJ', 39.3593749, -74.4222829, 'text_search', 'accepted from text search with matching identity context'),
    (480, 'ChIJv8jN7yZ-wokRHaT5Y1Z2F0g', '90 Division Ave, Levittown, NY 11756, USA', NULL, 'NY', 40.7269031, -73.5260571, 'text_search', 'accepted from text search with matching identity context'),
    (574, 'ChIJpaI0oKT5wokRVTxranSpDbo', '801 Rutherford Ave, Rutherford, NJ 07070, USA', 'Rutherford', 'NJ', 40.8114968, -74.1040834, 'place_id', 'accepted from existing google_place_id'),
    (1035, 'ChIJcTw_Z1hT2YARSlHHs8-bgrc', '818 Sixth Ave, San Diego, CA 92101, USA', NULL, 'CA', 32.713937, -117.15946749999998, 'text_search', 'accepted from text search with matching identity context'),
    (1036, 'ChIJJxkZR8V4bIcRHY8TkXuscXw', '1226 15th St, Denver, CO 80202, USA', NULL, 'CO', 39.7478957, -104.99837, 'text_search', 'accepted from text search with matching identity context'),
    (1046, 'ChIJYS2LnuXn5okRfKDnE8mKPHE', '29 Howard St, Springfield, MA 01105, USA', NULL, 'MA', 42.0990265, -72.5860804, 'text_search', 'accepted from text search with matching identity context'),
    (2291, 'ChIJ34GzxAG1QYgR1Phf4I5EFLY', 'The Comet, 4579 Hamilton Ave, Cincinnati, OH 45223, USA', NULL, 'OH', 39.1727984, -84.5432891, 'text_search', 'accepted from text search with matching identity context'),
    (2368, 'ChIJiwn8G1cr5ogRSVi8bIHK58k', '500 NE 9th St, Ocala, FL 34470, USA', 'Ocala', 'FL', 29.195424799999994, -82.13165959999999, 'place_id', 'accepted from existing google_place_id'),
    (2501, 'ChIJa4T_r7TvwIkRgUBQCNLz6f0', 'Borgata Hotel, Casino & Spa, 1 Borgata Way, Atlantic City, NJ 08401, USA', 'Atlantic City', 'NJ', 39.3783214, -74.4351921, 'place_id', 'accepted from existing google_place_id'),
    (2571, 'ChIJv4L0BlhmZIgRpAjXDGkM2KI', '505 Deaderick St, Nashville, TN 37243, USA', NULL, 'TN', 36.1649458, -86.781918, 'text_search', 'accepted from text search with matching identity context'),
    (2577, 'ChIJQ-UBfCFJ6IkR6JyfEPlAbXA', '71 E Main St, Patchogue, NY 11772, USA', 'Patchogue', 'NY', 40.765881199999995, -73.0134775, 'place_id', 'accepted from existing google_place_id'),
    (2583, 'ChIJB-7DbKStGYgRyHIT1HXtFTI', '975 Ottawa Ave NW, Grand Rapids, MI 49503, USA', 'Grand Rapids', 'MI', 42.979755999999995, -85.670791, 'place_id', 'accepted from existing google_place_id'),
    (2584, 'ChIJ98cKiInEwogRfyDonUPi2bc', '711 N Franklin St, Tampa, FL 33602, USA', 'Tampa', 'FL', 27.9503523, -82.4589293, 'place_id', 'accepted from existing google_place_id'),
    (2585, 'ChIJmY1Oo64B2YgRmRrO3WR5fyM', '707 NE 8th St, Fort Lauderdale, FL 33304, USA', 'Fort Lauderdale', 'FL', 26.134332999999998, -80.1362059, 'place_id', 'accepted from existing google_place_id'),
    (2586, 'ChIJk4OMimfd3ogRYWEWrsYvUVQ', '59 SW Flagler Ave, Stuart, FL 34994, USA', 'Stuart', 'FL', 27.199415, -80.25437900000001, 'place_id', 'accepted from existing google_place_id'),
    (2625, 'ChIJq00VWkvuwIkR-43gYiADWPw', 'Borgata Hotel, Casino & Spa, The Water Club, 1 Borgata Way, Atlantic City, NJ 08401, USA', 'Atlantic City', 'NJ', 39.3765814, -74.4363429, 'place_id', 'accepted from existing google_place_id'),
    (2812, 'ChIJdZk1_kDZEYgRXPNkSkcMjVo', '777 Casino Center Dr, Hammond, IN 46320, USA', 'Hammond', 'IN', 41.6940992, -87.5057441, 'place_id', 'accepted from existing google_place_id'),
    (2813, 'ChIJkbwYDZ0SkIARDZ1v1u9g7pw', '242 E Main St, Stockton, CA 95202, USA', 'Stockton', 'CA', 37.9524154, -121.28751369999999, 'place_id', 'accepted from existing google_place_id'),
    (2816, 'ChIJscNp2cGTtocR_YoV-qatlqo', '8330 Riverside Pkwy, Tulsa, OK 74137, USA', 'Tulsa', 'OK', 36.041916199999996, -95.9638914, 'place_id', 'accepted from existing google_place_id'),
    (2818, 'ChIJe5vwwIoYnlQRRJ9XoCYvQcI', '334 W Spokane Falls Blvd, Spokane, WA 99201, USA', 'Spokane', 'WA', 47.660555599999995, -117.4172222, 'place_id', 'accepted from existing google_place_id'),
    (2822, 'ChIJU_Waz0CEToYR41kE_v-m-0w', '1001 Texas Trust Wy, Grand Prairie, TX 75050, USA', 'Grand Prairie', 'TX', 32.7668573, -96.9823914, 'place_id', 'accepted from existing google_place_id'),
    (2823, 'ChIJ-epd9D7EyIAR0_A83lJWLf0', '3355 S Las Vegas Blvd, Las Vegas, NV 89109, USA', 'Las Vegas', 'NV', 36.121212899999996, -115.16936520000002, 'place_id', 'accepted from existing google_place_id'),
    (2825, 'ChIJed8cqZNSrlIRvbI-dJZkfVo', '350 Harbor Dr, Duluth, MN 55802, USA', 'Duluth', 'MN', 46.7799611, -92.0988101, 'place_id', 'accepted from existing google_place_id'),
    (2831, 'ChIJcVtbLQBDzoARCTGXyZmsg8c', '2121 S Casino Dr, Laughlin, NV 89029, USA', NULL, 'NV', 35.1576557, -114.57611929999999, 'text_search', 'accepted from text search with matching identity context'),
    (2836, 'ChIJ6xuoSw-1RIYRl2bhcYygHEk', '310 W Willie Nelson Blvd, Austin, TX 78701, USA', 'Austin', 'TX', 30.265262699999997, -97.7469912, 'place_id', 'accepted from existing google_place_id'),
    (2837, 'ChIJpY898VWKUocRRkIW8_tuZRE', '50 W 200 S, Salt Lake City, UT 84101, USA', 'Salt Lake City', 'UT', 40.7653384, -111.8927757, 'place_id', 'accepted from existing google_place_id'),
    (2839, 'ChIJUWtaNRmZ7ocR51AgAywQMDk', '1501 Woodland Ave, Des Moines, IA 50314, USA', 'Des Moines', 'IA', 41.5887311, -93.6383267, 'place_id', 'accepted from existing google_place_id'),
    (2840, 'ChIJGy-djFdrYogReL1vfKvzxvA', '700 Monroe St SW, Huntsville, AL 35801, USA', 'Huntsville', 'AL', 34.728040299999996, -86.5902136, 'place_id', 'accepted from existing google_place_id'),
    (2841, 'ChIJqS3PF1bzWYgRf_buIzGq-Pg', '87 Haywood St, Asheville, NC 28801, USA', 'Asheville', 'NC', 35.5977161, -82.5555711, 'place_id', 'accepted from existing google_place_id'),
    (2842, 'ChIJoze0RqC21okRRtyN-xw1Pl4', '200 W Ridge Rd, Rochester, NY 14615, USA', 'Rochester', 'NY', 43.1975043, -77.6327701, 'place_id', 'accepted from existing google_place_id'),
    (2843, 'ChIJJy8aA9Jz04kR0ph4A4JUSXk', '103 Center for the Arts, Buffalo, NY 14260, USA', 'Buffalo', 'NY', 43.000962, -78.7828622, 'place_id', 'accepted from existing google_place_id'),
    (2844, 'ChIJA7c-ygi5CIgRpPe60pvw3kA', '7801 E State St, Rockford, IL 61107, USA', 'Rockford', 'IL', 42.2700791, -88.96228049999999, 'place_id', 'accepted from existing google_place_id'),
    (2848, 'ChIJYR1mu8-tGYgRyl0hi0S_VdQ', '303 Monroe Ave NW, Grand Rapids, MI 49503, USA', 'Grand Rapids', 'MI', 42.9682258, -85.67307240000001, 'place_id', 'accepted from existing google_place_id'),
    (2849, 'ChIJe_vC2ZMbiYgR02QfzjUHfGA', '1817 3rd Ave N, Birmingham, AL 35203, USA', 'Birmingham', 'AL', 33.515115, -86.8091264, 'place_id', 'accepted from existing google_place_id'),
    (2850, 'ChIJe-AQq-4NTYgRuaDcXwwhhsk', '710 Williamson Rd NE, Roanoke, VA 24016, USA', 'Roanoke', 'VA', 37.280128399999995, -79.9358139, 'place_id', 'accepted from existing google_place_id'),
    (2852, 'ChIJx8c881AaxYkRH-IrmOI9q1E', '71 Public Square, Wilkes-Barre, PA 18701, USA', 'Wilkes-Barre', 'PA', 41.245185299999996, -75.8813866, 'place_id', 'accepted from existing google_place_id'),
    (2854, 'ChIJX2btPz7a5ogR1C_2BkLfq0Y', '600 Auditorium Blvd, Daytona Beach, FL 32118, USA', 'Daytona Beach', 'FL', 29.227165399999997, -81.0106174, 'place_id', 'accepted from existing google_place_id'),
    (2855, 'ChIJb8wDCWie-4gRHvsbBd2FOBo', 'Civic Center, 301 W Oglethorpe Ave, Savannah, GA 31401, USA', 'Savannah', 'GA', 32.0772056, -81.096733, 'place_id', 'accepted from existing google_place_id'),
    (2856, 'ChIJyRZlK2VeYIgRo3U1NwjUIEw', '399 McCallie Ave, Chattanooga, TN 37402, USA', 'Chattanooga', 'TN', 35.0480977, -85.3055555, 'place_id', 'accepted from existing google_place_id'),
    (2857, 'ChIJS_7hI8OjuokRGc33-9dASNQ', '3630 Victory Blvd, Portsmouth, VA 23701, USA', 'Portsmouth', 'VA', 36.8066932, -76.352946, 'place_id', 'accepted from existing google_place_id'),
    (2860, 'ChIJEdN5k4lYwokRuNPGGOZUwOQ', '2124 Broadway, New York, NY 10023, USA', 'New York', 'NY', 40.7804541, -73.9810962, 'place_id', 'accepted from existing google_place_id'),
    (2861, 'ChIJqWXnKOrjuocRNPJmSTEr-CQ', '200 N Broadway St, Wichita, KS 67202, USA', 'Wichita', 'KS', 37.688283399999996, -97.3353257, 'place_id', 'accepted from existing google_place_id'),
    (2862, 'ChIJQVBxwzwRsYkRbEJrgYsnoI8', '600 E Grace St Ste 400, Richmond, VA 23219, USA', 'Richmond', 'VA', 37.541585, -77.43703099999999, 'place_id', 'accepted from existing google_place_id'),
    (2864, 'ChIJScCHurrMj4AR3x6HUv5hclw', '135 W San Carlos St, San Jose, CA 95113, USA', 'San Jose', 'CA', 37.330784099999995, -121.8896922, 'place_id', 'accepted from existing google_place_id'),
    (2865, 'ChIJnYKYKO0_24gRiarZfbjCO4w', '13350 FSW Pkwy, Fort Myers, FL 33919, USA', 'Fort Myers', 'FL', 26.5513896, -81.88734749999999, 'place_id', 'accepted from existing google_place_id'),
    (2866, 'ChIJM_XTuRoKlVQRie3kKgoEGX4', '1037 SW Broadway, Portland, OR 97205, USA', 'Portland', 'OR', 45.5168624, -122.68115750000001, 'place_id', 'accepted from existing google_place_id'),
    (2871, 'ChIJFdIsDhMewVQRgaO3uAVsY54', '1 Eugene Center, Eugene, OR 97401, USA', 'Eugene', 'OR', 44.052743, -123.093179, 'place_id', 'accepted from existing google_place_id'),
    (2873, 'ChIJR9-hdSft0lQRnOxajtx51S8', '700 Auditorium Dr, Redding, CA 96001, USA', 'Redding', 'CA', 40.589521999999995, -122.379691, 'place_id', 'accepted from existing google_place_id'),
    (2874, 'ChIJu-ZMSWzkrIkR5y7cYEquZsI', '123 William V Bill Bell Wy, Durham, NC 27701, USA', 'Durham', 'NC', 35.993248, -78.9021923, 'place_id', 'accepted from existing google_place_id'),
    (2876, 'ChIJofmjs2ZHmYARJ-cirvqbkqU', '407 N Virginia St, Reno, NV 89501, USA', 'Reno', 'NV', 39.530501799999996, -119.8153353, 'place_id', 'accepted from existing google_place_id'),
    (2877, 'ChIJ1W7cDt15PIgRTWT5CNxYq4k', '4645 Heatherdowns Blvd, Toledo, OH 43614, USA', 'Toledo', 'OH', 41.592697400000006, -83.65181179999999, 'place_id', 'accepted from existing google_place_id'),
    (2879, 'ChIJYXAZtDygVogRQ8rHtsx6_QY', '900 Nc Music Factory Blvd B3, Charlotte, NC 28206, USA', 'Charlotte', 'NC', 35.23925, -80.84481, 'place_id', 'accepted from existing google_place_id'),
    (2881, 'ChIJ1Q3ZVn8E9YgRxZ015hv_l-w', '152 Luckie St NW, Atlanta, GA 30303, USA', 'Atlanta', 'GA', 33.7588551, -84.39140569999999, 'place_id', 'accepted from existing google_place_id'),
    (2886, 'ChIJfVia1HVyAHwRFFUnzuQLaWc', '2335 Kalākaua Ave, Honolulu, HI 96815, USA', 'Honolulu', 'HI', 21.2772447, -157.8270851, 'place_id', 'accepted from existing google_place_id'),
    (2926, 'ChIJ0TNasENiDogRy06isgSWSY0', '1401 Gateway Blvd, Joliet, IL 60431, USA', 'Joliet', 'IL', 41.496052899999995, -88.19059349999999, 'place_id', 'accepted from existing google_place_id'),
    (2950, 'ChIJXYrXrP1ZXIYRd64BYc-j-Ww', '104 N St Mary''s St, San Antonio, TX 78205, USA', 'San Antonio', 'TX', 29.424785599999996, -98.49109639999999, 'place_id', 'accepted from existing google_place_id'),
    (2952, 'ChIJ09FBbwy_QIYRy7QNN2j26_8', '401 Franklin St Ste 1600, Houston, TX 77201, USA', 'Houston', 'TX', 29.7659871, -95.3641092, 'place_id', 'accepted from existing google_place_id'),
    (2953, 'ChIJ7a3r1yGZToYRdUsgLzgV_MY', '1925 Elm St, Dallas, TX 75201, USA', 'Dallas', 'TX', 32.782698100000005, -96.794986, 'place_id', 'accepted from existing google_place_id'),
    (2955, 'ChIJk6QQWKUsDogR1vrLD_bdAEc', '175 N State St, Chicago, IL 60601, USA', 'Chicago', 'IL', 41.885297, -87.627753, 'place_id', 'accepted from existing google_place_id'),
    (2956, 'ChIJIQXeTw__kFQRZ2HjCncoymU', '2920 E R St, Tacoma, WA 98404, USA', 'Tacoma', 'WA', 47.237806299999995, -122.40817919999999, 'place_id', 'accepted from existing google_place_id'),
    (2959, 'ChIJYSyXSm3_v1QRzOCsol_HdCk', '170 High St SE, Salem, OR 97301, USA', 'Salem', 'OR', 44.9389172, -123.03734829999999, 'place_id', 'accepted from existing google_place_id'),
    (3000, 'ChIJddvT7zqDI4gRfabVvT2CFSI', '140 E 2nd St, Flint, MI 48502, USA', 'Flint', 'MI', 43.0153262, -83.6888932, 'place_id', 'accepted from existing google_place_id'),
    (3001, 'ChIJWfEyfDMtO4gRMVoXtqCDVPI', 'Fox Theatre, 2211 Woodward Ave, Detroit, MI 48201, USA', 'Detroit', 'MI', 42.338519, -83.052403, 'place_id', 'accepted from existing google_place_id'),
    (3002, 'ChIJIdgmcKTttocRGH5z_qHnlEY', '5970 E 31st St Ste A, Tulsa, OK 74135, USA', 'Tulsa', 'OK', 36.1183379, -95.90782329999999, 'place_id', 'accepted from existing google_place_id'),
    (3003, 'ChIJFdEl9GoiiYgRz4jWRUh-o9c', '1818 Data Dr, Hoover, AL 35244, USA', NULL, 'AL', 33.3765533, -86.7996962, 'text_search', 'accepted from text search with matching identity context'),
    (3007, 'ChIJpcLNN4e6t4kRWA8RnTLGUr4', '101 MGM National Ave, Forest Heights, MD 20745, USA', 'Forest Heights', 'MD', 38.795176, -77.0089483, 'place_id', 'accepted from existing google_place_id; corrected stale DB state from DC to MD'),
    (3008, 'ChIJiwV3rBXEyIARRdN3c345tKE', '3355 S Las Vegas Blvd, Las Vegas, NV 89109, USA', 'Las Vegas', 'NV', 36.121173999999996, -115.16965259999999, 'place_id', 'accepted from existing google_place_id'),
    (3009, 'ChIJlWTl3UHuwIkRULlNi9kSwNw', '777 Harrah''s Blvd, Atlantic City, NJ 08401, USA', 'Atlantic City', 'NJ', 39.3843392, -74.4276658, 'place_id', 'accepted from existing google_place_id'),
    (3016, 'ChIJBaLgyAtgXIYRYUim38RlDuU', '618 Northwest Loop 410 #312, San Antonio, TX 78216, USA', 'San Antonio', 'TX', 29.518436, -98.50272129999999, 'place_id', 'accepted from existing google_place_id'),
    (3018, 'ChIJYQ7Pcznv9IgRbv8GhVhrVoA', '175 Trilith Pkwy, Fayetteville, GA 30214, USA', 'Fayetteville', 'GA', 33.472294999999995, -84.50725039999999, 'place_id', 'accepted from existing google_place_id'),
    (3019, 'ChIJ1Ymtl0UY9YgR2lNZfLvLkcM', '5239 Floyd Rd SW, Mableton, GA 30126, USA', 'Mableton', 'GA', 33.8270708, -84.5726299, 'place_id', 'accepted from existing google_place_id'),
    (3021, 'ChIJY101yZBYrIkREiGioT3p1bo', '2 E South St, Raleigh, NC 27601, USA', 'Raleigh', 'NC', 35.7712601, -78.6396078, 'place_id', 'accepted from existing google_place_id'),
    (3022, 'ChIJeXoz-2juwIkR4DVGdUI-TkU', '2301 Boardwalk, Atlantic City, NJ 08401, USA', 'Atlantic City', 'NJ', 39.354904999999995, -74.438391, 'place_id', 'accepted from existing google_place_id'),
    (3024, 'ChIJFah1UoR15okRP8FB1DNU5ys', '350 Trolley Line Blvd, MASHANTUCKET, CT 06338, USA', 'MASHANTUCKET', 'CT', 41.4733358, -71.96000339999999, 'place_id', 'accepted from existing google_place_id'),
    (3032, 'ChIJ1wcJMn05QIcRVOB2xLg3Q2g', '320 E Hyman Ave, Aspen, CO 81611, USA', 'Aspen', 'CO', 39.1892778, -106.81997779999999, 'place_id', 'accepted from existing google_place_id'),
    (3045, 'ChIJ7YQxfL2p2YgR4E2OSYPIGXo', '8162 Melrose Ave, Los Angeles, CA 90046, USA', 'Los Angeles', 'CA', 34.083467399999996, -118.367408, 'place_id', 'accepted from existing google_place_id'),
    (3047, 'ChIJ0TNasENiDogRy06isgSWSY0', '1401 Gateway Blvd, Joliet, IL 60431, USA', NULL, 'IL', 41.496052899999995, -88.19059349999999, 'text_search', 'accepted from text search with matching identity context'),
    (4531, 'ChIJq00VWkvuwIkR-43gYiADWPw', 'Borgata Hotel, Casino & Spa, The Water Club, 1 Borgata Way, Atlantic City, NJ 08401, USA', NULL, 'NJ', 39.3765814, -74.4363429, 'text_search', 'accepted from text search with matching identity context'),
    (4603, 'ChIJtZl8uoH6MIgRIJlSUVz--lM', '1 Center Court, Cleveland, OH 44115, USA', NULL, 'OH', 41.4965474, -81.68805739999999, 'text_search', 'accepted from text search with matching identity context'),
    (4685, 'ChIJeTmHEoC80ocRAyVfuoLr8r8', '1 Simmons Bank Arena Dr, North Little Rock, AR 72114, USA', NULL, 'AR', 34.7550895, -92.26432349999999, 'text_search', 'accepted from text search with matching identity context'),
    (4703, 'ChIJASLBHoFW2YAR0YRjYwGJi04', '5500 Canyon Crest Dr, San Diego, CA 92182, USA', NULL, 'CA', 32.7740276, -117.07464420000001, 'text_search', 'accepted from text search with matching identity context'),
    (4707, 'ChIJ18hsDtqCa4cRrdYsOQfng3w', '18300 W Alameda Pkwy, Morrison, CO 80465, USA', NULL, 'CO', 39.6655381, -105.2052116, 'text_search', 'accepted from text search with matching identity context'),
    (4795, 'ChIJw1gIfmBfP4gRp6Vr6_IO5-I', 'Meredith Rd, Yellow Springs, OH 45387, USA', NULL, 'OH', 39.822435299999995, -83.86861259999999, 'text_search', 'accepted from text search with matching identity context'),
    (4861, 'ChIJMd064KnHxokRCTcp1DYABfQ', 'One Lincoln Financial Field Way, Philadelphia, PA 19148, USA', NULL, 'PA', 39.901418899999996, -75.1675992, 'text_search', 'accepted from text search with matching identity context'),
    (4909, 'ChIJvWCyh-bm5okRf2fL4mXhGIY', '1 MGM Wy, Springfield, MA 01103, USA', NULL, 'MA', 42.099947, -72.5877185, 'text_search', 'accepted from text search with matching identity context'),
    (4928, 'ChIJf5WmoCbTVHkRqN4qkZ2xcnc', '1 Cameron Way, Kahului, HI 96732, USA', NULL, 'HI', 20.893796899999998, -156.4807026, 'text_search', 'accepted from text search with matching identity context'),
    (4950, 'ChIJ7yDMhTYS04kRG3n5C7T1oWY', '1 Seymour H Knox III Plaza, Buffalo, NY 14203, USA', NULL, 'NY', 42.875081099999996, -78.8765439, 'text_search', 'accepted from text search with matching identity context'),
    (4970, 'ChIJP84-Q1cu34cRRoCJN1XQgOM', '1 Ameristar Blvd, St Charles, MO 63301, USA', NULL, 'MO', 38.766850999999996, -90.4839786, 'text_search', 'accepted from text search with matching identity context'),
    (5100, 'ChIJueAP_mHNFogR1IKaGW9k4yQ', '2010 Moose Krause Cir, Notre Dame, IN 46556, USA', NULL, 'IN', 41.6978278, -86.23130789999999, 'text_search', 'accepted from text search with matching identity context'),
    (5195, 'ChIJY3zWI_xTa4gRxWOAAZs0pGA', '610 W 46th St, Indianapolis, IN 46208, USA', NULL, 'IN', 39.8400555, -86.1694497, 'text_search', 'accepted from text search with matching identity context'),
    (5256, 'ChIJe32wh6lDlIARHnZpahhT7Tc', '2770 E International Ave, Fresno, CA 93730, USA', NULL, 'CA', 36.8894271, -119.73683159999999, 'text_search', 'accepted from text search with matching identity context'),
    (5257, 'ChIJJ1QnKFSh6IgR_f5rZZitx80', '250 Gale Lemerand Dr, Gainesville, FL 32611, USA', NULL, 'FL', 29.649422999999995, -82.35116819999999, 'text_search', 'accepted from text search with matching identity context'),
    (5266, 'ChIJqb8FnltZwoARBn8oZ1KtbIQ', '2723 Rancho Vista Blvd, Palmdale, CA 93551, USA', NULL, 'CA', 34.6032844, -118.1782278, 'text_search', 'accepted from text search with matching identity context'),
    (5321, 'ChIJSzkqU55w7ocR-e4Iu7kUlnE', '1900 Center Dr, Ames, IA 50011, USA', NULL, 'IA', 42.0202332, -93.6380186, 'text_search', 'accepted from text search with matching identity context'),
    (5400, 'ChIJz_PcoCQK3okRnQAzoKIMlak', 'Agency Building 1, S Mall Arterial, Albany, NY 12203, USA', NULL, 'NY', 42.650358, -73.75837, 'text_search', 'accepted from text search with matching identity context'),
    (5419, 'ChIJcdEWjbHiEogRURgZNQCNbe8', 'Stewart Center, 128 Memorial Mall Dr STEW G054, West Lafayette, IN 47907, USA', NULL, 'IN', 40.4253198, -86.91329739999999, 'text_search', 'accepted from text search with matching identity context'),
    (5420, 'ChIJBQUMhQ26b4gRy7fFG56l6nw', '1215 Hickman Ave, Owensboro, KY 42301, USA', NULL, 'KY', 37.7626807, -87.126148, 'text_search', 'accepted from text search with matching identity context'),
    (5457, 'ChIJ158jjo6Fk4cRaCtWfqz0n0k', '1 Arena Way, Council Bluffs, IA 51501, USA', NULL, 'IA', 41.237465, -95.890299, 'text_search', 'accepted from text search with matching identity context');

UPDATE clubs c
SET google_place_id = b.place_id,
    address = b.address,
    city = COALESCE(b.city, c.city),
    state = COALESCE(b.state, c.state),
    latitude = COALESCE(b.latitude, c.latitude),
    longitude = COALESCE(b.longitude, c.longitude),
    country = COALESCE(c.country, 'US'),
    description = concat_ws(
        E'\n\n',
        NULLIF(c.description, ''),
        'Updated by TASK-3027 via Google Places ' || b.source || ': ' || b.rationale
    )
FROM club_location_google_places_backfill b
WHERE c.id = b.club_id
  AND (c.address IS NULL OR btrim(c.address) = '' OR c.address <> b.address);

CREATE TEMP TABLE club_location_cleanup_classification (
    club_id integer PRIMARY KEY,
    action text NOT NULL,
    address text NOT NULL,
    rationale text NOT NULL
) ON COMMIT DROP;

INSERT INTO club_location_cleanup_classification (club_id, action, address, rationale)
VALUES
    (539, 'producer_trigger', 'Multiple venues, NJ/PA/DE/MD', 'Kricket Comedy is a multi-venue producer; Google Places query rejected Comedy Cellar false positive, and show names enumerate host venues across NJ/PA/DE/MD.'),
    (556, 'production_company', 'Production company office; multiple venues', 'Coastal Entertainment Productions is a multi-venue producer; existing Google place_id resolves to an office, not a show venue.'),
    (573, 'festival', 'Multiple venues, AZ', 'Big Pine Comedy Festival has no single Google Places venue hit; current schema intentionally represents festivals with clubs.club_type = festival.'),
    (620, 'producer_aggregator', 'Multiple venues, DC/MD/VA', 'Comedy Shows Near Me is a hidden multi-venue aggregator; Google Places query rejected Comedy Cellar false positive.'),
    (4036, 'platform_trigger', 'Platform trigger - no physical venue', 'Ticketmaster National is an intentional hidden platform trigger for ticketmaster_national discovery, not a public club.'),
    (8735, 'secret_location', 'Address disclosed after booking, Miami, FL', 'Eventbrite-style secret-location listing; no public Google Places address is available before booking.');

UPDATE clubs c
SET address = cls.address,
    description = concat_ws(
        E'\n\n',
        NULLIF(c.description, ''),
        'Reviewed by TASK-3027: ' || cls.rationale
    )
FROM club_location_cleanup_classification cls
WHERE c.id = cls.club_id
  AND (c.address IS NULL OR btrim(c.address) = '' OR c.address IS DISTINCT FROM cls.address);

INSERT INTO production_companies (name, slug, website, scraping_url, visible, show_name_keywords)
VALUES
    (
        'Kricket Comedy',
        'kricket-comedy',
        'https://www.kricketcomedy.com/',
        'https://www.kricketcomedy.com/',
        true,
        ARRAY['Kricket Comedy']::text[]
    ),
    (
        'Coastal Entertainment Productions',
        'coastal-entertainment-productions',
        'https://coastalentertainment.com',
        'https://coastalentertainment.com',
        false,
        ARRAY[]::text[]
    ),
    (
        'Comedy Shows Near Me',
        'comedy-shows-near-me',
        'https://www.comedyshowsnear.me/',
        'https://comedyshowsnear.me',
        false,
        ARRAY[]::text[]
    )
ON CONFLICT (slug) DO UPDATE
SET name = EXCLUDED.name,
    website = EXCLUDED.website,
    scraping_url = EXCLUDED.scraping_url,
    visible = EXCLUDED.visible,
    show_name_keywords = EXCLUDED.show_name_keywords;

UPDATE shows s
SET production_company_id = pc.id
FROM production_companies pc
WHERE s.club_id = 539
  AND pc.slug = 'kricket-comedy'
  AND s.production_company_id IS DISTINCT FROM pc.id;

UPDATE shows s
SET production_company_id = pc.id
FROM production_companies pc
WHERE s.club_id = 556
  AND pc.slug = 'coastal-entertainment-productions'
  AND s.production_company_id IS DISTINCT FROM pc.id;

UPDATE shows s
SET production_company_id = pc.id
FROM production_companies pc
WHERE s.club_id = 620
  AND pc.slug = 'comedy-shows-near-me'
  AND s.production_company_id IS DISTINCT FROM pc.id;

DO $$
DECLARE
    blank_count integer;
    unstamped_count integer;
BEGIN
    SELECT count(*) INTO blank_count
    FROM clubs
    WHERE address IS NULL OR btrim(address) = '';

    IF blank_count <> 0 THEN
        RAISE EXCEPTION 'TASK-3027 left % clubs with blank addresses', blank_count;
    END IF;

    SELECT count(*) INTO unstamped_count
    FROM shows s
    WHERE s.club_id IN (539, 556, 620)
      AND s.production_company_id IS NULL;

    IF unstamped_count <> 0 THEN
        RAISE EXCEPTION 'TASK-3027 left % producer/aggregator shows without production_company_id', unstamped_count;
    END IF;
END $$;
