-- Onboard ComedyTickets audit candidates with more than 4 upcoming events.
--
-- Source CSV: /private/tmp/comedytickets-candidates-with-counts.csv
-- Generated from rows where comedytickets_event_count > 4 after excluding
-- rows that already matched an existing club by normalized name or address.
-- ComedyTickets is an aggregator/ticketing surface, not a first-party club
-- site, so these are hidden club shells with no scraping_sources rows. They
-- preserve the venue identity for later first-party website/scraper onboarding
-- without routing users to ComedyTickets.
--
-- Idempotency: this migration also guards every insert against existing clubs
-- by normalized name and by normalized street+state at apply time.
--
-- 2026-07-07 (pre-apply review): added a same-city containment guard — a
-- candidate is also skipped when its normalized name contains (or is contained
-- by) an existing club's normalized name in the same city+state, with the
-- shorter side at least 8 normalized chars. This catches showtime variants
-- ("Tacoma Comedy Club - Downtown - 7PM"), rooms ("Comedy Mothership - Fat
-- Man"), and renames ("Big Laugh Comedy Club Fort Worth" vs the onboarded
-- "Big Laugh Comedy Club") that exact-equality misses, while keeping
-- legitimately distinct cross-city siblings (e.g. Helium Buffalo).

WITH candidates (name, address, website, city, state, zip_code, country, club_type, description, source_ids, source_event_count) AS (
  VALUES
    ('3Arena', 'Dublin', '', 'Dublin', NULL, NULL, NULL, 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 1786; ComedyTickets upcoming event count at audit time: 7. First-party website not yet verified.', '1786', 7),
    ('Agora Theater & Ballroom', 'Cleveland, OH', '', 'Cleveland', 'OH', NULL, 'US', 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 1127; ComedyTickets upcoming event count at audit time: 5. First-party website not yet verified.', '1127', 5),
    ('Ann Arbor Comedy Showcase', '212 S 4th Ave, Ann Arbor, MI 48104, Ann Arbor, MI', '', 'Ann Arbor', 'MI', '48104', 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 139; ComedyTickets upcoming event count at audit time: 46. First-party website not yet verified.', '139', 46),
    ('Aquila''s Nest Vineyard', 'Sandy Hook, CT', '', 'Sandy Hook', 'CT', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 2597; ComedyTickets upcoming event count at audit time: 11. First-party website not yet verified.', '2597', 11),
    ('Arlington Music Hall', '224 N Center St, Arlington, TX', '', 'Arlington', 'TX', NULL, 'US', 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 16031; ComedyTickets upcoming event count at audit time: 5. First-party website not yet verified.', '16031', 5),
    ('Aruba Ray''s Comedy Club', 'J.E. Irausquin Blvd 248, Eagle Beach, Aruba, Eagle Beach', '', 'Eagle Beach', NULL, NULL, NULL, 'club', 'Discovered from ComedyTickets audit; source venue id(s): 159; ComedyTickets upcoming event count at audit time: 20. First-party website not yet verified.', '159', 20),
    ('B.B. King''s Blues Club', 'Orlando, FL', '', 'Orlando', 'FL', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 2033; ComedyTickets upcoming event count at audit time: 7. First-party website not yet verified.', '2033', 7),
    ('Bay St. Louis Little Theatre', 'Bay St. Louis, MS', '', 'Bay St. Louis', 'MS', NULL, 'US', 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 2639; ComedyTickets upcoming event count at audit time: 6. First-party website not yet verified.', '2639', 6),
    ('Beach Cove Resort', 'North Myrtle Beach, SC', '', 'North Myrtle Beach', 'SC', NULL, 'US', 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 2827; ComedyTickets upcoming event count at audit time: 7. First-party website not yet verified.', '2827', 7),
    ('Bert Kreischer''s Fully Loaded at Sea 2026', 'Miami, FL', '', 'Miami', 'FL', NULL, 'US', 'festival', 'Discovered from ComedyTickets audit; source venue id(s): 8304; ComedyTickets upcoming event count at audit time: 5. First-party website not yet verified.', '8304', 5),
    ('Big Laugh Comedy Club Fort Worth', '604 Main St, Suite 100, Fort Worth, TX 76102, Fort Worth, TX', '', 'Fort Worth', 'TX', '76102', 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 160, 161; ComedyTickets upcoming event count at audit time: 135. First-party website not yet verified.', '160, 161', 135),
    ('Boom Chicago', 'Rozengracht 117, Amsterdam, Netherlands', '', 'Netherlands', NULL, NULL, NULL, 'club', 'Discovered from ComedyTickets audit; source venue id(s): 540; ComedyTickets upcoming event count at audit time: 8. First-party website not yet verified.', '540', 8),
    ('Bottlerocket Social Hall', 'Pittsburgh, PA', '', 'Pittsburgh', 'PA', NULL, 'US', 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 596; ComedyTickets upcoming event count at audit time: 6. First-party website not yet verified.', '596', 6),
    ('Bricktown Comedy Club - Oklahoma City', 'Oklahoma City, OK', '', 'Oklahoma City', 'OK', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 3268; ComedyTickets upcoming event count at audit time: 15. First-party website not yet verified.', '3268', 15),
    ('Brignole Vineyards', 'East Granby, CT', '', 'East Granby', 'CT', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 2594; ComedyTickets upcoming event count at audit time: 6. First-party website not yet verified.', '2594', 6),
    ('Bristol Hippodrome', 'Bristol', '', 'Bristol', NULL, NULL, NULL, 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 1894; ComedyTickets upcoming event count at audit time: 5. First-party website not yet verified.', '1894', 5),
    ('Broadway Theatre of Pitman', 'Pitman, NJ', '', 'Pitman', 'NJ', NULL, 'US', 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 566; ComedyTickets upcoming event count at audit time: 5. First-party website not yet verified.', '566', 5),
    ('Chattanooga, TN', 'Chattanooga, TN', '', 'Chattanooga', 'TN', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 2264; ComedyTickets upcoming event count at audit time: 6. First-party website not yet verified.', '2264', 6),
    ('Chatterbox Jazz Club', '435 Massachusetts Ave, Indianapolis, IN', '', 'Indianapolis', 'IN', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 16032; ComedyTickets upcoming event count at audit time: 5. First-party website not yet verified.', '16032', 5),
    ('City Winery - New York', 'New York, NY', '', 'New York', 'NY', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 780; ComedyTickets upcoming event count at audit time: 7. First-party website not yet verified.', '780', 7),
    ('Claude''s Comedy Club & Bar', 'Philadelphia, PA', '', 'Philadelphia', 'PA', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 6017; ComedyTickets upcoming event count at audit time: 18. First-party website not yet verified.', '6017', 18),
    ('Club 337', 'Lafayette, LA', '', 'Lafayette', 'LA', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 807; ComedyTickets upcoming event count at audit time: 18. First-party website not yet verified.', '807', 18),
    ('Club Regent Event Centre', 'Winnipeg, MB', '', 'Winnipeg', 'MB', NULL, 'CA', 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 1381; ComedyTickets upcoming event count at audit time: 5. First-party website not yet verified.', '1381', 5),
    ('Club Soda', 'Montreal, Quebec', '', 'Quebec', NULL, NULL, NULL, 'club', 'Discovered from ComedyTickets audit; source venue id(s): 6614; ComedyTickets upcoming event count at audit time: 5. First-party website not yet verified.', '6614', 5),
    ('Comedy Bar - Danforth', 'Toronto, ON', '', 'Toronto', 'ON', NULL, 'CA', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 546; ComedyTickets upcoming event count at audit time: 26. First-party website not yet verified.', '546', 26),
    ('Comedy Bar - Toronto', 'Toronto, ON', '', 'Toronto', 'ON', NULL, 'CA', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 552; ComedyTickets upcoming event count at audit time: 14. First-party website not yet verified.', '552', 14),
    ('Comedy Cellar', 'Las Vegas, NV', '', 'Las Vegas', 'NV', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 1760; ComedyTickets upcoming event count at audit time: 14. First-party website not yet verified.', '1760', 14),
    ('Comedy Mothership - Fat Man', 'Austin, TX', '', 'Austin', 'TX', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 905; ComedyTickets upcoming event count at audit time: 19. First-party website not yet verified.', '905', 19),
    ('Comedy Store - Los Angeles (Belly Room)', 'West Hollywood, CA', '', 'West Hollywood', 'CA', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 3338; ComedyTickets upcoming event count at audit time: 5. First-party website not yet verified.', '3338', 5),
    ('Count Basie Center for the Arts', 'Red Bank, NJ', '', 'Red Bank', 'NJ', NULL, 'US', 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 511; ComedyTickets upcoming event count at audit time: 6. First-party website not yet verified.', '511', 6),
    ('Dallas Comedy Club', 'Dallas, TX', '', 'Dallas', 'TX', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 4325, 4326, 505; ComedyTickets upcoming event count at audit time: 211. First-party website not yet verified.', '4325, 4326, 505', 211),
    ('DC Comedy Loft and Bier Baron Tavern', 'Washington, DC', '', 'Washington', 'DC', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 583; ComedyTickets upcoming event count at audit time: 21. First-party website not yet verified.', '583', 21),
    ('Denver Improv Comedy Theater and Restaurant', 'Denver, CO', '', 'Denver', 'CO', NULL, 'US', 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 1139; ComedyTickets upcoming event count at audit time: 37. First-party website not yet verified.', '1139', 37),
    ('Des Moines Social Club', 'Des Moines, IA', '', 'Des Moines', 'IA', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 2349; ComedyTickets upcoming event count at audit time: 6. First-party website not yet verified.', '2349', 6),
    ('Dr. Grins Comedy Club at The B.O.B.', 'Grand Rapids, MI', '', 'Grand Rapids', 'MI', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 611; ComedyTickets upcoming event count at audit time: 13. First-party website not yet verified.', '611', 13),
    ('Eccles Theater', 'Salt Lake City, UT', '', 'Salt Lake City', 'UT', NULL, 'US', 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 1503; ComedyTickets upcoming event count at audit time: 5. First-party website not yet verified.', '1503', 5),
    ('Edinburgh Playhouse', 'Edinburgh', '', 'Edinburgh', NULL, NULL, NULL, 'club', 'Discovered from ComedyTickets audit; source venue id(s): 1895; ComedyTickets upcoming event count at audit time: 6. First-party website not yet verified.', '1895', 6),
    ('Elgin and Winter Garden Theatre Centre', '189 Yonge St #620, Toronto, ON', '', 'Toronto', 'ON', NULL, 'CA', 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 3278; ComedyTickets upcoming event count at audit time: 6. First-party website not yet verified.', '3278', 6),
    ('Ensemble Arts Philly', 'Philadelphia, PA', '', 'Philadelphia', 'PA', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 1995; ComedyTickets upcoming event count at audit time: 5. First-party website not yet verified.', '1995', 5),
    ('Eventim Apollo', 'London', '', 'London', NULL, NULL, NULL, 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 1787; ComedyTickets upcoming event count at audit time: 12. First-party website not yet verified.', '1787', 12),
    ('Fallout Theater', '616 Lavaca St, Austin, TX 78701, Austin, TX', '', 'Austin', 'TX', '78701', 'US', 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 128; ComedyTickets upcoming event count at audit time: 12. First-party website not yet verified.', '128', 12),
    ('Fat Black Pussycat', '130 W 3rd St, New York, NY 10012, New York, NY', '', 'New York', 'NY', '10012', 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 7; ComedyTickets upcoming event count at audit time: 19. First-party website not yet verified.', '7', 19),
    ('Flop House Comedy Club', '362 Grand St, Brooklyn, NY 11211, Brooklyn, NY', '', 'Brooklyn', 'NY', '11211', 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 3; ComedyTickets upcoming event count at audit time: 12. First-party website not yet verified.', '3', 12),
    ('Funny Bone Comedy Club - Albany', 'Albany, NY', '', 'Albany', 'NY', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 604; ComedyTickets upcoming event count at audit time: 25. First-party website not yet verified.', '604', 25),
    ('Funny Bone Comedy Club - Cincinnati', 'Liberty Township, OH', '', 'Liberty Township', 'OH', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 647; ComedyTickets upcoming event count at audit time: 13. First-party website not yet verified.', '647', 13),
    ('Funny Bone Comedy Club - Cleveland', 'Cleveland, OH', '', 'Cleveland', 'OH', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 736; ComedyTickets upcoming event count at audit time: 16. First-party website not yet verified.', '736', 16),
    ('Funny Bone Comedy Club - Kansas City', 'Kansas City, MO', '', 'Kansas City', 'MO', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 600; ComedyTickets upcoming event count at audit time: 18. First-party website not yet verified.', '600', 18),
    ('Funny Bone Comedy Club - St. Louis', 'St. Louis, MO', '', 'St. Louis', 'MO', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 3366; ComedyTickets upcoming event count at audit time: 6. First-party website not yet verified.', '3366', 6),
    ('Funny Bone Comedy Club - Syracuse', 'Syracuse, NY', '', 'Syracuse', 'NY', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 3311; ComedyTickets upcoming event count at audit time: 30. First-party website not yet verified.', '3311', 30),
    ('Funny Bone Comedy Club - Toledo', 'Perrysburg, OH', '', 'Perrysburg', 'OH', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 3288; ComedyTickets upcoming event count at audit time: 13. First-party website not yet verified.', '3288', 13),
    ('Funny Bone Comedy Club Omaha NE', 'Omaha, NE', '', 'Omaha', 'NE', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 1454; ComedyTickets upcoming event count at audit time: 19. First-party website not yet verified.', '1454', 19),
    ('Funny Bone Comedy Club Orlando FL', 'Orlando, FL', '', 'Orlando', 'FL', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 480; ComedyTickets upcoming event count at audit time: 16. First-party website not yet verified.', '480', 16),
    ('Funnybone Des Moines', 'Des Moines, IA', '', 'Des Moines', 'IA', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 649; ComedyTickets upcoming event count at audit time: 13. First-party website not yet verified.', '649', 13),
    ('FUNY Stand Up Classes', 'New York, NY', '', 'New York', 'NY', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 4156; ComedyTickets upcoming event count at audit time: 6. First-party website not yet verified.', '4156', 6),
    ('Greenwich Village Comedy Club', '99 MacDougal St, New York, NY 10012, New York, NY', '', 'New York', 'NY', '10012', 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 9; ComedyTickets upcoming event count at audit time: 100. First-party website not yet verified.', '9', 100),
    ('Ha Ha Cafe Comedy Club', 'North Hollywood, CA', '', 'North Hollywood', 'CA', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 99; ComedyTickets upcoming event count at audit time: 24. First-party website not yet verified.', '99', 24),
    ('Harrah''s Las Vegas', 'Las Vegas, NV', '', 'Las Vegas', 'NV', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 2179; ComedyTickets upcoming event count at audit time: 8. First-party website not yet verified.', '2179', 8),
    ('Helium Comedy Club - Buffalo', 'Buffalo, NY', '', 'Buffalo', 'NY', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 732; ComedyTickets upcoming event count at audit time: 22. First-party website not yet verified.', '732', 22),
    ('High Line Comedy Club', '446 W 14th St, New York, NY 10014, New York, NY', '', 'New York', 'NY', '10014', 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 2; ComedyTickets upcoming event count at audit time: 6. First-party website not yet verified.', '2', 6),
    ('Hotel Blackfoot', 'Calgary, AB', '', 'Calgary', 'AB', NULL, 'CA', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 2832; ComedyTickets upcoming event count at audit time: 5. First-party website not yet verified.', '2832', 5),
    ('House of Comedy Bloomington MN', 'Bloomington, MN', '', 'Bloomington', 'MN', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 1122; ComedyTickets upcoming event count at audit time: 14. First-party website not yet verified.', '1122', 14),
    ('House of Comedy New Westminster BC', 'New Westminster, BC', '', 'New Westminster', 'BC', NULL, 'CA', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 1124; ComedyTickets upcoming event count at audit time: 7. First-party website not yet verified.', '1124', 7),
    ('Howler Comedy Club', 'Lincoln, NE', '', 'Lincoln', 'NE', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 977; ComedyTickets upcoming event count at audit time: 5. First-party website not yet verified.', '977', 5),
    ('Hyena''s Comedy Night Club - Albuquerque', '2100 Louisiana Blvd NE #434, Albuquerque, NM', '', 'Albuquerque', 'NM', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 620; ComedyTickets upcoming event count at audit time: 59. First-party website not yet verified.', '620', 59),
    ('Hyena''s Comedy Night Club - Dallas', '5321 E Mockingbird Ln, Dallas, TX', '', 'Dallas', 'TX', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 584; ComedyTickets upcoming event count at audit time: 55. First-party website not yet verified.', '584', 55),
    ('Hyena''s Comedy Nightclub Fort Worth', '425 Commerce Street, Fort Worth, TX', '', 'Fort Worth', 'TX', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 353; ComedyTickets upcoming event count at audit time: 55. First-party website not yet verified.', '353', 55),
    ('Kellar''s Comedy Club', 'Erie, PA', '', 'Erie', 'PA', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 899; ComedyTickets upcoming event count at audit time: 5. First-party website not yet verified.', '899', 5),
    ('KGB Bar Red Room', 'New York, NY', '', 'New York', 'NY', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 725; ComedyTickets upcoming event count at audit time: 5. First-party website not yet verified.', '725', 5),
    ('L''Olympia', 'Montreal, QC', '', 'Montreal', 'QC', NULL, 'CA', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 1752; ComedyTickets upcoming event count at audit time: 7. First-party website not yet verified.', '1752', 7),
    ('L.A. Comedy Club''s Dragon Room', 'Las Vegas, NV', '', 'Las Vegas', 'NV', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 1126; ComedyTickets upcoming event count at audit time: 7. First-party website not yet verified.', '1126', 7),
    ('Lafayette Comedy', 'Lafayette, LA', '', 'Lafayette', 'LA', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 806; ComedyTickets upcoming event count at audit time: 5. First-party website not yet verified.', '806', 5),
    ('Laugh Factory at Horseshoe Las Vegas', 'Las Vegas, NV', '', 'Las Vegas', 'NV', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 3290; ComedyTickets upcoming event count at audit time: 29. First-party website not yet verified.', '3290', 29),
    ('Laugh Lounge', 'Ottawa, ON', '', 'Ottawa', 'ON', NULL, 'CA', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 773; ComedyTickets upcoming event count at audit time: 5. First-party website not yet verified.', '773', 5),
    ('Laugh Out Loud - San Antonio', 'San Antonio, TX', '', 'San Antonio', 'TX', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 619; ComedyTickets upcoming event count at audit time: 7. First-party website not yet verified.', '619', 7),
    ('Laugh Out Loud Comedy Club', 'San Antonio, TX', '', 'San Antonio', 'TX', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 273; ComedyTickets upcoming event count at audit time: 56. First-party website not yet verified.', '273', 56),
    ('Laugh Shop Calgary', 'Calgary, AB', '', 'Calgary', 'AB', NULL, 'CA', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 441; ComedyTickets upcoming event count at audit time: 14. First-party website not yet verified.', '441', 14),
    ('Laughs Comedy Club', '5220 Roosevelt Way NE, Seattle, WA 98105, Seattle, WA', '', '5220 Roosevelt Way NE', 'NE', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 129; ComedyTickets upcoming event count at audit time: 16. First-party website not yet verified.', '129', 16),
    ('Laughs Unlimited Comedy Club and Lounge', 'Sacramento, CA', '', 'Sacramento', 'CA', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 499; ComedyTickets upcoming event count at audit time: 7. First-party website not yet verified.', '499', 7),
    ('Le Point Virgule', 'Paris', '', 'Paris', NULL, NULL, NULL, 'club', 'Discovered from ComedyTickets audit; source venue id(s): 1271; ComedyTickets upcoming event count at audit time: 10. First-party website not yet verified.', '1271', 10),
    ('Leicester Square Theatre', 'London, England', '', 'England', NULL, NULL, NULL, 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 817; ComedyTickets upcoming event count at audit time: 9. First-party website not yet verified.', '817', 9),
    ('Levity Live Oxnard', 'Oxnard, CA', '', 'Oxnard', 'CA', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 105; ComedyTickets upcoming event count at audit time: 45. First-party website not yet verified.', '105', 45),
    ('Lexington, KY', '161 Lexington Green Cir # C4, Lexington, KY', '', 'Lexington', 'KY', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 9660; ComedyTickets upcoming event count at audit time: 12. First-party website not yet verified.', '9660', 12),
    ('Lillian S. Wells Hall at The Parker', 'Ft Lauderdale, FL', '', 'Ft Lauderdale', 'FL', NULL, 'US', 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 1135; ComedyTickets upcoming event count at audit time: 8. First-party website not yet verified.', '1135', 8),
    ('Loony Bin Comedy Club - Little Rock', 'Little Rock, AR', '', 'Little Rock', 'AR', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 3317; ComedyTickets upcoming event count at audit time: 13. First-party website not yet verified.', '3317', 13),
    ('Loony Bin Comedy Club - Tulsa', 'Tulsa, OK', '', 'Tulsa', 'OK', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 500; ComedyTickets upcoming event count at audit time: 34. First-party website not yet verified.', '500', 34),
    ('Loony Bin Comedy Club - Wichita', 'Wichita, KS', '', 'Wichita', 'KS', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 6078; ComedyTickets upcoming event count at audit time: 9. First-party website not yet verified.', '6078', 9),
    ('Loony Bin Comedy Club Little Rock AR', '10301 N Rodney Parham Rd, Little Rock, AR 72227, Little Rock, AR', '', 'Little Rock', 'AR', '72227', 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 167; ComedyTickets upcoming event count at audit time: 5. First-party website not yet verified.', '167', 5),
    ('Loony Bin Comedy Club Wichita KS', 'Wichita, KS', '', 'Wichita', 'KS', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 8685; ComedyTickets upcoming event count at audit time: 5. First-party website not yet verified.', '8685', 5),
    ('Lounge At The End Of The Universe', '2417 Bank Dr, Boise, ID', '', 'Boise', 'ID', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 377; ComedyTickets upcoming event count at audit time: 9. First-party website not yet verified.', '377', 9),
    ('Martha Vineyard Comedy Fest - Week 2', 'Oak Bluffs, MA', '', 'Oak Bluffs', 'MA', NULL, 'US', 'festival', 'Discovered from ComedyTickets audit; source venue id(s): 1458; ComedyTickets upcoming event count at audit time: 5. First-party website not yet verified.', '1458', 5),
    ('Mayo Civic Center', 'Rochester, MN', '', 'Rochester', 'MN', NULL, 'US', 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 801; ComedyTickets upcoming event count at audit time: 5. First-party website not yet verified.', '801', 5),
    ('Monkey Barrel Comedy', 'Edinburgh, Scotland', '', 'Scotland', NULL, NULL, NULL, 'club', 'Discovered from ComedyTickets audit; source venue id(s): 6050; ComedyTickets upcoming event count at audit time: 25. First-party website not yet verified.', '6050', 25),
    ('Monkey Barrell Comedy', 'Edinburgh, UK', '', 'UK', NULL, NULL, NULL, 'club', 'Discovered from ComedyTickets audit; source venue id(s): 14019; ComedyTickets upcoming event count at audit time: 23. First-party website not yet verified.', '14019', 23),
    ('Neon Room at Helium Comedy Club', 'Portland, OR', '', 'Portland', 'OR', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 639; ComedyTickets upcoming event count at audit time: 5. First-party website not yet verified.', '639', 5),
    ('New Jersey Performing Arts Center', 'Newark, NJ', '', 'Newark', 'NJ', NULL, 'US', 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 482; ComedyTickets upcoming event count at audit time: 6. First-party website not yet verified.', '482', 6),
    ('New York Comedy Club - Stamford', '230 Tresser Blvd, Stamford, CT 06901, Stamford, CT', '', 'Stamford', 'CT', '06901', 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 405; ComedyTickets upcoming event count at audit time: 100. First-party website not yet verified.', '405', 100),
    ('North Charleston Coliseum & Performing Arts Center', 'North Charleston, SC', '', 'North Charleston', 'SC', NULL, 'US', 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 509; ComedyTickets upcoming event count at audit time: 5. First-party website not yet verified.', '509', 5),
    ('O2 Apollo Manchester', 'Manchester', '', 'Manchester', NULL, NULL, NULL, 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 1846; ComedyTickets upcoming event count at audit time: 9. First-party website not yet verified.', '1846', 9),
    ('Old National Centre', 'Indianapolis, IN', '', 'Indianapolis', 'IN', NULL, 'US', 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 1300; ComedyTickets upcoming event count at audit time: 5. First-party website not yet verified.', '1300', 5),
    ('Olsen Run Comedy Club and Lounge', 'Eugene, OR', '', 'Eugene', 'OR', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 477; ComedyTickets upcoming event count at audit time: 30. First-party website not yet verified.', '477', 30),
    ('Open Mic at FUNY Stand Up Classes', 'New York, NY', '', 'New York', 'NY', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 731; ComedyTickets upcoming event count at audit time: 14. First-party website not yet verified.', '731', 14),
    ('OVO Hydro', 'Glasgow', '', 'Glasgow', NULL, NULL, NULL, 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 1893; ComedyTickets upcoming event count at audit time: 12. First-party website not yet verified.', '1893', 12),
    ('Playhouse Square', 'Cleveland, OH', '', 'Cleveland', 'OH', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 529; ComedyTickets upcoming event count at audit time: 5. First-party website not yet verified.', '529', 5),
    ('Punch Line Dallas', 'Irving, TX', '', 'Irving', 'TX', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 654; ComedyTickets upcoming event count at audit time: 33. First-party website not yet verified.', '654', 33),
    ('Punch Line Philadelphia', 'Philadelphia, PA', '', 'Philadelphia', 'PA', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 12591; ComedyTickets upcoming event count at audit time: 17. First-party website not yet verified.', '12591', 17),
    ('Punchline Comedy Club - Atlanta', 'Atlanta, GA', '', 'Atlanta', 'GA', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 503; ComedyTickets upcoming event count at audit time: 11. First-party website not yet verified.', '503', 11),
    ('Quezada''s Comedy Club & Catina', 'Santa Ana Pueblo, NM', '', 'Santa Ana Pueblo', 'NM', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 628; ComedyTickets upcoming event count at audit time: 51. First-party website not yet verified.', '628', 51),
    ('Rebecca Cohn Auditorium', 'Halifax, NS', '', 'Halifax', 'NS', NULL, 'CA', 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 1850; ComedyTickets upcoming event count at audit time: 5. First-party website not yet verified.', '1850', 5),
    ('Rialto Casper', 'Casper, WY', '', 'Casper', 'WY', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 1283; ComedyTickets upcoming event count at audit time: 16. First-party website not yet verified.', '1283', 16),
    ('Rialto Theatre', 'Tucson, AZ', '', 'Tucson', 'AZ', NULL, 'US', 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 527; ComedyTickets upcoming event count at audit time: 8. First-party website not yet verified.', '527', 8),
    ('Rick Bronson''s - The Comic Strip', 'Edmonton, AB', '', 'Edmonton', 'AB', NULL, 'CA', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 1092; ComedyTickets upcoming event count at audit time: 9. First-party website not yet verified.', '1092', 9),
    ('Rick Bronson''s House of Comedy BC', 'New Westminster, BC', '', 'New Westminster', 'BC', NULL, 'CA', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 680; ComedyTickets upcoming event count at audit time: 23. First-party website not yet verified.', '680', 23),
    ('Rio Suite Hotel & Casino', 'Las Vegas, NV', '', 'Las Vegas', 'NV', NULL, 'US', 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 1583; ComedyTickets upcoming event count at audit time: 15. First-party website not yet verified.', '1583', 15),
    ('River: A Waterfront Restaurant and Bar', 'Wethersfield, CT', '', 'Wethersfield', 'CT', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 2595; ComedyTickets upcoming event count at audit time: 24. First-party website not yet verified.', '2595', 24),
    ('Robert Kirk Walker Theatre', 'Chattanooga, TN', '', 'Chattanooga', 'TN', NULL, 'US', 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 1103; ComedyTickets upcoming event count at audit time: 5. First-party website not yet verified.', '1103', 5),
    ('Room 52', 'New York, NY', '', 'New York', 'NY', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 4155; ComedyTickets upcoming event count at audit time: 26. First-party website not yet verified.', '4155', 26),
    ('Rose City Comedy - 9PM', '117 W Front St, Tyler, TX', '', 'Tyler', 'TX', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 3342; ComedyTickets upcoming event count at audit time: 16. First-party website not yet verified.', '3342', 16),
    ('Salle Pierre Mercure', 'Montreal, QC', '', 'Montreal', 'QC', NULL, 'CA', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 2339; ComedyTickets upcoming event count at audit time: 8. First-party website not yet verified.', '2339', 8),
    ('San Antonio Improv', '849 E Commerce St #311, San Antonio, TX 78205, San Antonio, TX', '', 'San Antonio', 'TX', '78205', 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 404; ComedyTickets upcoming event count at audit time: 55. First-party website not yet verified.', '404', 55),
    ('Saratoga Springs City Center', 'Saratoga Springs, NY', '', 'Saratoga Springs', 'NY', NULL, 'US', 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 784; ComedyTickets upcoming event count at audit time: 6. First-party website not yet verified.', '784', 6),
    ('Seattle', 'Seattle, WA', '', 'Seattle', 'WA', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 14202; ComedyTickets upcoming event count at audit time: 6. First-party website not yet verified.', '14202', 6),
    ('Sesh Comedy, Chrystie', 'New York, NY', '', 'New York', 'NY', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 3270; ComedyTickets upcoming event count at audit time: 13. First-party website not yet verified.', '3270', 13),
    ('Silver Legacy Resort Casino', 'Reno, NV', '', 'Reno', 'NV', NULL, 'US', 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 1137; ComedyTickets upcoming event count at audit time: 20. First-party website not yet verified.', '1137', 20),
    ('Skankfest New Orleans', 'New Orleans, LA', '', 'New Orleans', 'LA', NULL, 'US', 'festival', 'Discovered from ComedyTickets audit; source venue id(s): 8193; ComedyTickets upcoming event count at audit time: 7. First-party website not yet verified.', '8193', 7),
    ('Skyline Comedy Cafe', 'Appleton, WI', '', 'Appleton', 'WI', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 85; ComedyTickets upcoming event count at audit time: 100. First-party website not yet verified.', '85', 100),
    ('Skyline Comedy Club - 7PM', 'Appleton, WI', '', 'Appleton', 'WI', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 2359; ComedyTickets upcoming event count at audit time: 21. First-party website not yet verified.', '2359', 21),
    ('Soul Joel''s', 'Pottstown, PA', '', 'Pottstown', 'PA', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 577; ComedyTickets upcoming event count at audit time: 12. First-party website not yet verified.', '577', 12),
    ('Soul Joel''s Comedy Club & Lounge', '401 S. Schuylkill Ave, Jeffersonville, Jeffersonville,, PA', '', 'Jeffersonville', 'PA', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 320; ComedyTickets upcoming event count at audit time: 5. First-party website not yet verified.', '320', 5),
    ('SPORTS DRINK: Cafe & Comedy Club', 'New Orleans, LA', '', 'New Orleans', 'LA', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 504; ComedyTickets upcoming event count at audit time: 37. First-party website not yet verified.', '504', 37),
    ('St. Andy''s Sports Pub', 'Panama City, FL', '', 'Panama City', 'FL', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 2640; ComedyTickets upcoming event count at audit time: 23. First-party website not yet verified.', '2640', 23),
    ('St. Louis', 'St. Louis, MO', '', 'St. Louis', 'MO', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 1091; ComedyTickets upcoming event count at audit time: 5. First-party website not yet verified.', '1091', 5),
    ('Stand Up Live', 'Phoenix, AZ', '', 'Phoenix', 'AZ', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 1095; ComedyTickets upcoming event count at audit time: 26. First-party website not yet verified.', '1095', 26),
    ('Stir Crazy Comedy Club', '6751 N Sunset Blvd, Ste E-206, Glendale, AZ 85305, Glendale, AZ', '', 'Glendale', 'AZ', '85305', 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 165; ComedyTickets upcoming event count at audit time: 12. First-party website not yet verified.', '165', 12),
    ('Stress Factory - Valley Forge Casino', 'King of Prussia, PA', '', 'King of Prussia', 'PA', NULL, 'US', 'venue', 'Discovered from ComedyTickets audit; source venue id(s): 912; ComedyTickets upcoming event count at audit time: 6. First-party website not yet verified.', '912', 6),
    ('Stress Factory Comedy Club - New Brunswick', 'New Brunswick, NJ', '', 'New Brunswick', 'NJ', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 3314; ComedyTickets upcoming event count at audit time: 22. First-party website not yet verified.', '3314', 22),
    ('Super Funny Comedy Club', '8402 S Hosmer St, Tacoma, WA 98444, Tacoma, WA', '', 'Tacoma', 'WA', '98444', 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 84; ComedyTickets upcoming event count at audit time: 50. First-party website not yet verified.', '84', 50),
    ('Tacoma Comedy Club - 6th and Proctor', 'Tacoma, WA', '', 'Tacoma', 'WA', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 447; ComedyTickets upcoming event count at audit time: 34. First-party website not yet verified.', '447', 34),
    ('Tacoma Comedy Club - Downtown - 7PM', 'Tacoma, WA', '', 'Tacoma', 'WA', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 1336; ComedyTickets upcoming event count at audit time: 8. First-party website not yet verified.', '1336', 8),
    ('Talk to the Moon Comedy Club', 'Pensacola, FL', '', 'Pensacola', 'FL', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 16093; ComedyTickets upcoming event count at audit time: 8. First-party website not yet verified.', '16093', 8),
    ('Tampa, FL', 'Tampa, FL', '', 'Tampa', 'FL', NULL, 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 1141; ComedyTickets upcoming event count at audit time: 7. First-party website not yet verified.', '1141', 7),
    ('The American Comedy Co.', '818 6th Ave, San Diego, CA 92101, San Diego, CA', '', 'San Diego', 'CA', '92101', 'US', 'club', 'Discovered from ComedyTickets audit; source venue id(s): 171; ComedyTickets upcoming event count at audit time: 20. First-party website not yet verified.', '171', 20)
)
INSERT INTO clubs (name, address, website, city, state, zip_code, country, club_type, description, visible, status)
SELECT c.name, c.address, c.website, c.city, c.state, c.zip_code, c.country, c.club_type, c.description, FALSE, 'active'
FROM candidates c
WHERE NOT EXISTS (
    SELECT 1
    FROM clubs existing
    WHERE regexp_replace(lower(existing.name), '[^a-z0-9]+', '', 'g') = regexp_replace(lower(c.name), '[^a-z0-9]+', '', 'g')
       OR (
            c.state IS NOT NULL
        AND regexp_replace(lower(split_part(existing.address, ',', 1)), '[^a-z0-9]+', '', 'g') <> ''
        AND regexp_replace(lower(split_part(c.address, ',', 1)), '[^a-z0-9]+', '', 'g') <> ''
        AND regexp_replace(lower(split_part(existing.address, ',', 1)), '[^a-z0-9]+', '', 'g') = regexp_replace(lower(split_part(c.address, ',', 1)), '[^a-z0-9]+', '', 'g')
        AND COALESCE(existing.state, '') = COALESCE(c.state, '')
       )
       OR (
            lower(COALESCE(existing.city, '')) = lower(COALESCE(c.city, ''))
        AND COALESCE(existing.state, '') = COALESCE(c.state, '')
        AND least(
              length(regexp_replace(lower(existing.name), '[^a-z0-9]+', '', 'g')),
              length(regexp_replace(lower(c.name), '[^a-z0-9]+', '', 'g'))
            ) >= 8
        AND (
              position(regexp_replace(lower(existing.name), '[^a-z0-9]+', '', 'g') in regexp_replace(lower(c.name), '[^a-z0-9]+', '', 'g')) > 0
           OR position(regexp_replace(lower(c.name), '[^a-z0-9]+', '', 'g') in regexp_replace(lower(existing.name), '[^a-z0-9]+', '', 'g')) > 0
        )
       )
);
